// Package protocolgen generates the TypeScript and Rust mirrors of the frozen
// desktop bridge wire schema, so a v1 field lives in one document instead of
// three hand-maintained copies.
package protocolgen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

// SchemaPath is the frozen wire schema every generated artifact derives from.
const SchemaPath = "docs/tauri/protocol/v1.schema.json"

// Artifact is one deterministic generated file, relative to the repository root.
type Artifact struct {
	Path string
	Data []byte
}

// The generated mirrors. Go stays hand-written: it owns the wire format and
// the schema is a description of it rather than its source.
const (
	TypeScriptArtifactPath = "desktop/frontend/src/lib/bridgeProtocol.generated.ts"
	RustArtifactPath       = "desktop/tauri/src/protocol_generated.rs"
)

type document struct {
	Defs map[string]json.RawMessage `json:"$defs"`
}

type node struct {
	Ref        string                     `json:"$ref"`
	Title      string                     `json:"title"`
	Type       string                     `json:"type"`
	Enum       []string                   `json:"enum"`
	Const      json.RawMessage            `json:"const"`
	Required   []string                   `json:"required"`
	Properties map[string]json.RawMessage `json:"properties"`
	Items      json.RawMessage            `json:"items"`
}

type field struct {
	jsonName string
	rustName string
	tsType   string
	rustType string
	optional bool
}

type named struct {
	name   string
	fields []field
}

type generator struct {
	defs  map[string]json.RawMessage
	types map[string]*named
	order []string
}

// Generate builds every wire mirror from the schema. It never reads the
// committed outputs, so a stale artifact cannot feed back into a new one.
func Generate(root string) ([]Artifact, error) {
	defs, err := loadSchema(root)
	if err != nil {
		return nil, err
	}

	g := &generator{defs: defs, types: map[string]*named{}}
	keys := make([]string, 0, len(defs))
	for key := range defs {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		if _, _, err := g.typeOf(defs[key], defName(key, defs[key])); err != nil {
			return nil, fmt.Errorf("$defs.%s: %w", key, err)
		}
	}

	ordered := make([]*named, 0, len(g.order))
	sort.Strings(g.order)
	for _, name := range g.order {
		ordered = append(ordered, g.types[name])
	}
	return []Artifact{
		{Path: TypeScriptArtifactPath, Data: renderTypeScript(ordered)},
		{Path: RustArtifactPath, Data: renderRust(ordered)},
	}, nil
}

func loadSchema(root string) (map[string]json.RawMessage, error) {
	raw, err := os.ReadFile(filepath.Join(root, SchemaPath))
	if err != nil {
		return nil, fmt.Errorf("read wire schema: %w", err)
	}
	var doc document
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("decode wire schema: %w", err)
	}
	if len(doc.Defs) == 0 {
		return nil, fmt.Errorf("wire schema %s declares no $defs", SchemaPath)
	}
	return doc.Defs, nil
}

// Check reports the first artifact that differs from what the schema produces.
func Check(root string, artifacts []Artifact) error {
	for _, artifact := range artifacts {
		committed, err := os.ReadFile(filepath.Join(root, artifact.Path))
		if err != nil {
			return fmt.Errorf("read %s: %w", artifact.Path, err)
		}
		if !bytes.Equal(committed, artifact.Data) {
			return fmt.Errorf("%s is stale; run go run ./cmd/desktop-bridge-protocol-gen", artifact.Path)
		}
	}
	return nil
}

// Write replaces every artifact with the generated bytes.
func Write(root string, artifacts []Artifact) error {
	for _, artifact := range artifacts {
		path := filepath.Join(root, artifact.Path)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create %s: %w", filepath.Dir(artifact.Path), err)
		}
		if err := os.WriteFile(path, artifact.Data, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", artifact.Path, err)
		}
	}
	return nil
}

// typeOf maps one schema node to its TypeScript and Rust spellings. Object
// nodes are registered as named types and reported by name in both languages.
func (g *generator) typeOf(raw json.RawMessage, hint string) (string, string, error) {
	var n node
	if err := json.Unmarshal(raw, &n); err != nil {
		return "", "", fmt.Errorf("decode node: %w", err)
	}
	if n.Ref != "" {
		key, err := defKey(n.Ref)
		if err != nil {
			return "", "", err
		}
		target, ok := g.defs[key]
		if !ok {
			return "", "", fmt.Errorf("$ref %q matches no declaration", n.Ref)
		}
		return g.typeOf(target, defName(key, target))
	}
	if len(n.Enum) > 0 {
		quoted := make([]string, 0, len(n.Enum))
		for _, value := range n.Enum {
			quoted = append(quoted, fmt.Sprintf("%q", value))
		}
		return strings.Join(quoted, " | "), "String", nil
	}
	// A string const is a one-value enum: keep the literal in TypeScript and
	// fall back to String in Rust, which has no literal types.
	if len(n.Const) > 0 {
		var literal string
		if err := json.Unmarshal(n.Const, &literal); err == nil {
			return fmt.Sprintf("%q", literal), "String", nil
		}
	}
	switch n.Type {
	case "string":
		return "string", "String", nil
	case "boolean":
		return "boolean", "bool", nil
	case "integer":
		return "number", "u64", nil
	case "array":
		if len(n.Items) == 0 {
			return "", "", fmt.Errorf("array declares no items")
		}
		ts, rust, err := g.typeOf(n.Items, hint+"Item")
		if err != nil {
			return "", "", err
		}
		return ts + "[]", "Vec<" + rust + ">", nil
	case "object":
		if len(n.Properties) == 0 {
			return "Record<string, unknown>", "Value", nil
		}
		name := n.Title
		if name == "" {
			name = hint
		}
		if name == "" {
			return "", "", fmt.Errorf("object needs a title or a naming hint")
		}
		if err := g.register(name, n); err != nil {
			return "", "", err
		}
		return name, name, nil
	case "":
		return "", "", fmt.Errorf("node declares no type, enum or $ref")
	default:
		return "", "", fmt.Errorf("unsupported type %q", n.Type)
	}
}

func (g *generator) register(name string, n node) error {
	if _, ok := g.types[name]; ok {
		return nil
	}
	required := make(map[string]bool, len(n.Required))
	for _, key := range n.Required {
		required[key] = true
	}
	keys := make([]string, 0, len(n.Properties))
	for key := range n.Properties {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	fields := make([]field, 0, len(keys))
	for _, key := range keys {
		ts, rust, err := g.typeOf(n.Properties[key], name+pascal(key))
		if err != nil {
			return fmt.Errorf("%s.%s: %w", name, key, err)
		}
		optional := !required[key]
		rustName := camelToSnake(key)
		if rustKeywords[rustName] {
			return fmt.Errorf("%s.%s maps to the Rust keyword %q", name, key, rustName)
		}
		if optional {
			rust = "Option<" + rust + ">"
		}
		fields = append(fields, field{
			jsonName: key,
			rustName: rustName,
			tsType:   ts,
			rustType: rust,
			optional: optional,
		})
	}
	g.types[name] = &named{name: name, fields: fields}
	g.order = append(g.order, name)
	return nil
}

func renderTypeScript(types []*named) []byte {
	blocks := make([]string, 0, len(types))
	for _, t := range types {
		var b strings.Builder
		fmt.Fprintf(&b, "export interface %s {\n", t.name)
		for _, f := range t.fields {
			marker := ""
			if f.optional {
				marker = "?"
			}
			fmt.Fprintf(&b, "  %s%s: %s;\n", f.jsonName, marker, f.tsType)
		}
		b.WriteString("}")
		blocks = append(blocks, b.String())
	}
	header := fmt.Sprintf("// Code generated by cmd/desktop-bridge-protocol-gen from %s. DO NOT EDIT.\n\n", SchemaPath)
	return []byte(header + strings.Join(blocks, "\n\n") + "\n")
}

func renderRust(types []*named) []byte {
	blocks := make([]string, 0, len(types))
	for _, t := range types {
		var b strings.Builder
		b.WriteString("#[derive(Clone, Debug, Deserialize, Serialize)]\n")
		b.WriteString("#[serde(rename_all = \"camelCase\")]\n")
		fmt.Fprintf(&b, "pub struct %s {\n", t.name)
		for _, f := range t.fields {
			fmt.Fprintf(&b, "    pub %s: %s,\n", f.rustName, f.rustType)
		}
		b.WriteString("}")
		blocks = append(blocks, b.String())
	}
	header := fmt.Sprintf("// Code generated by cmd/desktop-bridge-protocol-gen from %s. DO NOT EDIT.\n\n", SchemaPath)
	imports := "#![allow(dead_code)]\n\nuse serde::{Deserialize, Serialize};\nuse serde_json::Value;\n\n"
	return []byte(header + imports + strings.Join(blocks, "\n\n") + "\n")
}

func defKey(ref string) (string, error) {
	const prefix = "#/$defs/"
	if !strings.HasPrefix(ref, prefix) || len(ref) == len(prefix) {
		return "", fmt.Errorf("unsupported $ref %q; only %s<name> is generated", ref, prefix)
	}
	return strings.TrimPrefix(ref, prefix), nil
}

func defName(key string, raw json.RawMessage) string {
	var n node
	if err := json.Unmarshal(raw, &n); err == nil && n.Title != "" {
		return n.Title
	}
	return "Bridge" + pascal(key)
}

func pascal(value string) string {
	runes := []rune(value)
	if len(runes) == 0 {
		return value
	}
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func camelToSnake(value string) string {
	var b strings.Builder
	for i, r := range value {
		if unicode.IsUpper(r) {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(unicode.ToLower(r))
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

var rustKeywords = map[string]bool{
	"as": true, "break": true, "const": true, "continue": true, "crate": true,
	"dyn": true, "else": true, "enum": true, "extern": true, "false": true,
	"fn": true, "for": true, "if": true, "impl": true, "in": true, "let": true,
	"loop": true, "match": true, "mod": true, "move": true, "mut": true,
	"pub": true, "ref": true, "return": true, "self": true, "static": true,
	"struct": true, "super": true, "trait": true, "true": true, "type": true,
	"unsafe": true, "use": true, "where": true, "while": true, "async": true,
	"await": true, "box": true, "final": true, "macro": true, "override": true,
	"priv": true, "try": true, "typeof": true, "unsized": true, "virtual": true,
	"yield": true,
}
