// Code generated by cmd/desktop-bridge-protocol-gen from docs/tauri/protocol/v1.schema.json. DO NOT EDIT.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeAnswerQuestionRequest {
    pub answers: Vec<BridgeAskAnswer>,
    pub id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeApprovalRequest {
    pub allow: bool,
    pub id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeAskAnswer {
    pub question_id: String,
    pub selected: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeAttachFileRequest {
    pub path: String,
    pub session_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeAttachment {
    pub is_image: bool,
    pub name: String,
    pub path: String,
    pub size: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeAttachmentResponse {
    pub attachment: BridgeAttachment,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeCodeRewindCommitRequest {
    pub confirm_partial_coverage: bool,
    pub plan_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeCodeRewindPlanResponse {
    pub plan: BridgeWorkspaceCodeRewindPlan,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeCodeRewindPreviewRequest {
    pub turn: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeCombinedRewindCommitRequest {
    pub confirm_partial_coverage: bool,
    pub plan_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeCombinedRewindPlanResponse {
    pub plan: BridgeWorkspaceCombinedRewindPlan,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeCombinedRewindPreviewRequest {
    pub turn: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeCombinedRewindResultResponse {
    pub protocol_version: u64,
    pub result: BridgeWorkspaceCombinedRewindResult,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeConversationRewindCommitRequest {
    pub plan_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeConversationRewindPlanResponse {
    pub plan: BridgeWorkspaceConversationRewindPlan,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeConversationRewindPreviewRequest {
    pub turn: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeConversationRewindResultResponse {
    pub protocol_version: u64,
    pub result: BridgeWorkspaceConversationRewindResult,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeConversationRewindUndoRequest {
    pub head_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeDeleteSessionResponse {
    pub deleted: bool,
    pub protocol_version: u64,
    pub session_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeError {
    pub error: BridgeErrorBody,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeErrorBody {
    pub code: String,
    pub message: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeEvent {
    pub event_kind: String,
    pub payload: Value,
    pub protocol_version: u64,
    pub sequence: u64,
    pub session_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tab_id: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeHealth {
    pub capabilities: Vec<String>,
    pub protocol_version: u64,
    pub sidecar_instance_id: String,
    pub status: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeHistoryMessage {
    pub content: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at_ms: Option<u64>,
    pub role: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub truncated: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub turn_usage: Option<BridgeHistoryTurnUsage>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub work_duration_ms: Option<u64>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeHistoryResponse {
    pub messages: Vec<BridgeHistoryMessage>,
    pub protocol_version: u64,
    pub sequence: u64,
    pub session: BridgeSession,
    pub start_index: u64,
    pub total_messages: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeHistoryTurnUsage {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_hit_tokens: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_miss_tokens: Option<u64>,
    pub complete: bool,
    pub estimated: bool,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub reasoning_tokens: u64,
    pub request_count: u64,
    pub total_tokens: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeLegacyConversationForkResult {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    pub ok: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeLegacyConversationForkResultResponse {
    pub protocol_version: u64,
    pub result: BridgeLegacyConversationForkResult,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeMCPInteractionAnswerRequest {
    pub action: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<Value>,
    pub id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeOpenSessionRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_ref: Option<String>,
    pub session_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeProjectFolder {
    pub root: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeProjectFoldersResponse {
    pub projects: Vec<BridgeProjectFolder>,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeProviderModelProbeRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    pub model: String,
    pub name: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeProviderModelProbeResponse {
    pub latency_millis: u64,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeProviderReasoningSummary {
    pub default: String,
    pub levels: Vec<String>,
    pub model: String,
    pub selected: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeProviderSummary {
    pub configured: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    pub kind: String,
    pub model_count: u64,
    pub models: Vec<String>,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<Vec<BridgeProviderReasoningSummary>>,
    pub requires_key: bool,
    pub search_models: Vec<String>,
    pub vision_models: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeProviderSummaryResponse {
    pub compact_ratio_percent: f64,
    pub default_model: String,
    pub planner_model: String,
    pub protocol_version: u64,
    pub providers: Vec<BridgeProviderSummary>,
    pub reasoning_language: String,
    pub scope: String,
    pub vision_model: String,
    pub web_search_model: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteBrowseEntry {
    pub is_dir: bool,
    pub mod_time: u64,
    pub name: String,
    pub path: String,
    pub size: u64,
    pub symlink: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteBrowseRequest {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteBrowseResponse {
    pub entries: Vec<BridgeRemoteBrowseEntry>,
    pub parent_path: String,
    pub path: String,
    pub protocol_version: u64,
    pub truncated: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteConnectRequest {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub passphrase: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trust_fingerprint: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteConnectResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fingerprint: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    pub protocol_version: u64,
    pub status: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerCloseResponse {
    pub closed: bool,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerHistoryMessage {
    pub content: String,
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub missing: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub protocol_recovery: Option<BridgeRemoteControllerProtocolRecovery>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<String>,
    pub role: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub server_search: Option<Vec<BridgeRemoteControllerHistorySearch>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<BridgeRemoteControllerHistoryToolCall>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_name: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerHistorySearch {
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<BridgeRemoteControllerHistorySearchHit>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "sources_status")]
    pub sources_status: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerHistorySearchHit {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerHistoryToolCall {
    pub arguments: String,
    pub id: String,
    pub name: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerImage {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mime: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size: Option<u64>,
    pub url: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerProjectionReplay {
    pub events: Vec<Value>,
    pub floor_seq: u64,
    pub has_more: bool,
    pub latest_seq: u64,
    pub next_after_seq: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_epoch: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerProjectionRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub continuation: Option<String>,
    pub session_path: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerProtocolRecovery {
    pub id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerRequest {
    pub name: String,
    pub workspace: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerResponse {
    pub controller: BridgeRemoteControllerView,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerRuntimeState {
    pub activity: String,
    pub background_jobs: u64,
    pub cancel_requested: bool,
    pub cancellable: bool,
    pub pending_prompt: bool,
    pub phase: String,
    pub revision: u64,
    pub running: bool,
    pub runtime_epoch: String,
    pub schema_version: u64,
    pub turn_event_seq: u64,
    pub turn_id: String,
    pub turn_status: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerSession {
    pub current: bool,
    pub mtime_milli: u64,
    pub name: String,
    pub path: String,
    pub running: bool,
    pub taken_over: bool,
    pub title: String,
    pub turns: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerSessionCancelReceipt {
    pub cancelled: bool,
    pub protocol_version: u64,
    pub runtime_epoch: String,
    pub session_path: String,
    pub turn_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerSessionCancelRequest {
    pub runtime_epoch: String,
    pub session_path: String,
    pub turn_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerSessionCancelResponse {
    pub controller: BridgeRemoteControllerView,
    pub protocol_version: u64,
    pub receipt: BridgeRemoteControllerSessionCancelReceipt,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerSessionEvent {
    pub controller: BridgeRemoteControllerView,
    pub event: Value,
    pub protocol_version: u64,
    pub session_path: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerSessionImageRequest {
    pub session_path: String,
    pub source: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerSessionImageResponse {
    pub controller: BridgeRemoteControllerView,
    pub protocol_version: u64,
    pub view: BridgeRemoteControllerSessionImageView,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerSessionImageView {
    pub image: BridgeRemoteControllerImage,
    pub protocol_version: u64,
    pub session_path: String,
    pub workspace: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerSessionProjection {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_turn_id: Option<String>,
    pub history: Vec<BridgeRemoteControllerHistoryMessage>,
    pub initial: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page_token: Option<String>,
    pub protocol_version: u64,
    pub read_only: bool,
    pub replay: BridgeRemoteControllerProjectionReplay,
    pub replay_after_seq: u64,
    pub session_path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub turn_status: Option<String>,
    pub user_suffix: Vec<BridgeRemoteControllerHistoryMessage>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerSessionProjectionResponse {
    pub controller: BridgeRemoteControllerView,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_page: Option<String>,
    pub projection: BridgeRemoteControllerSessionProjection,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerSessionView {
    pub current: bool,
    pub history: Vec<BridgeRemoteControllerHistoryMessage>,
    pub label: String,
    pub model_ref: String,
    pub ownership: String,
    pub protocol_version: u64,
    pub read_only: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime_state: Option<BridgeRemoteControllerRuntimeState>,
    pub session_path: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerSessionViewRequest {
    pub session_path: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerSessionViewResponse {
    pub controller: BridgeRemoteControllerView,
    pub protocol_version: u64,
    pub view: BridgeRemoteControllerSessionView,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerSessionsResponse {
    pub controller: BridgeRemoteControllerView,
    pub protocol_version: u64,
    pub sessions: Vec<BridgeRemoteControllerSession>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteControllerView {
    pub id: String,
    pub name: String,
    pub read_only: bool,
    pub workspace: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteDisconnectRequest {
    pub name: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteDisconnectResponse {
    pub disconnected: bool,
    pub name: String,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteFilePreviewRequest {
    pub name: String,
    pub path: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteFilePreviewResponse {
    pub content: String,
    pub kind: String,
    pub path: String,
    pub protocol_version: u64,
    pub revision: String,
    pub truncated: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteFileSaveRequest {
    pub content: String,
    pub name: String,
    pub path: String,
    pub revision: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteFileSaveResponse {
    pub path: String,
    pub protocol_version: u64,
    pub revision: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRenameSessionRequest {
    pub title: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSession {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effort: Option<String>,
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_ref: Option<String>,
    pub path: String,
    pub state: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSessionHeadSwitchRequest {
    pub head_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSessionHeadSwitchResponse {
    pub ok: bool,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSessionHeadView {
    pub id: String,
    pub kind: String,
    pub message_count: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preview: Option<String>,
    pub selected: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSessionHeadsResponse {
    pub heads: Vec<BridgeSessionHeadView>,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSessionMetrics {
    pub cache_hit_tokens: u64,
    pub cache_miss_tokens: u64,
    pub compact_threshold_percent: u64,
    pub context_used_tokens: u64,
    pub context_window_tokens: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSessionResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metrics: Option<BridgeSessionMetrics>,
    pub protocol_version: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<u64>,
    pub session: BridgeSession,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSetAgentPreferenceRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compact_ratio_percent: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_language: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSetDefaultModelRequest {
    pub model: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSetModelRoleRequest {
    pub model: String,
    pub role: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSetSessionModelRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effort: Option<String>,
    pub model: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSubmitRequest {
    pub input: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeTerminalActionResponse {
    pub accepted: bool,
    pub protocol_version: u64,
    pub terminal_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeTerminalCreateRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shell_id: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeTerminalExitView {
    pub exit_code: i64,
    pub id: String,
    pub removed: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeTerminalInputRequest {
    pub data: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeTerminalOutputResponse {
    pub output: BridgeTerminalOutputView,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeTerminalOutputView {
    pub data: String,
    pub end: u64,
    pub id: String,
    pub start: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeTerminalRenameRequest {
    pub title: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeTerminalResizeRequest {
    pub cols: u64,
    pub rows: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeTerminalSessionResponse {
    pub protocol_version: u64,
    pub terminal: BridgeTerminalSessionView,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeTerminalSessionView {
    pub created_at: u64,
    pub cwd: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i64>,
    pub id: String,
    pub running: bool,
    pub shell: String,
    pub title: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeTerminalShellView {
    pub id: String,
    pub label: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeTerminalWorkspaceResponse {
    pub protocol_version: u64,
    pub workspace: BridgeTerminalWorkspaceView,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeTerminalWorkspaceView {
    pub available: bool,
    pub read_only: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub sessions: Vec<BridgeTerminalSessionView>,
    pub shells: Vec<BridgeTerminalShellView>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceChangeDetail {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub added: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub binary: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub diff: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub removed: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub truncated: Option<bool>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceChangeDetailRequest {
    pub path: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceChangeDetailResponse {
    pub detail: BridgeWorkspaceChangeDetail,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceChangeView {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub can_session_revert: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub git_status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latest_prompt: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latest_time: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub old_path: Option<String>,
    pub path: String,
    pub sources: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub turns: Option<Vec<u64>>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceChanges {
    pub files: Vec<BridgeWorkspaceChangeView>,
    pub git_available: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub git_branch: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub git_err: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceChangesResponse {
    pub changes: BridgeWorkspaceChanges,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceCheckpointView {
    pub prompt: String,
    pub time: u64,
    pub turn: u64,
    pub turn_file_count: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceCheckpointsResponse {
    pub checkpoints: Vec<BridgeWorkspaceCheckpointView>,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceCodeRewindPlan {
    pub can_files: bool,
    pub conflicts: Vec<String>,
    pub coverage: String,
    pub coverage_gaps: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disabled_reason: Option<String>,
    pub file_count: u64,
    pub files: Vec<String>,
    pub files_truncated: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plan_id: Option<String>,
    pub requires_coverage_confirmation: bool,
    pub turn: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceCombinedRewindPlan {
    pub can_conversation: bool,
    pub can_files: bool,
    pub conflicts: Vec<String>,
    pub coverage_gaps: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disabled_reason: Option<String>,
    pub file_count: u64,
    pub files: Vec<String>,
    pub files_truncated: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plan_id: Option<String>,
    pub requires_coverage_confirmation: bool,
    pub turn: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceCombinedRewindResult {
    pub conflicts: Vec<String>,
    pub conversation_forked: bool,
    pub deleted_count: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    pub files_restored: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub head_id: Option<String>,
    pub ok: bool,
    pub partial: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
    pub undo_available: bool,
    pub written_count: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceConversationRewindPlan {
    pub can_conversation: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disabled_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plan_id: Option<String>,
    pub turn: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceConversationRewindResult {
    pub conversation_forked: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub head_id: Option<String>,
    pub ok: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceEntry {
    pub is_dir: bool,
    pub name: String,
    pub path: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFilePreview {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub binary: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    pub path: String,
    pub size: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub truncated: Option<bool>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileRequest {
    pub path: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileResponse {
    pub preview: BridgeWorkspaceFilePreview,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileRevertCommitRequest {
    pub plan_id: String,
    pub resolution: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileRevertPlan {
    pub can_files: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conflicts: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disabled_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub legacy: Option<bool>,
    pub path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plan_id: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileRevertPlanResponse {
    pub plan: BridgeWorkspaceFileRevertPlan,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileRevertResult {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conflicts: Option<Vec<String>>,
    pub deleted_count: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    pub ok: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
    pub undo_available: bool,
    pub written_count: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileRevertResultResponse {
    pub protocol_version: u64,
    pub result: BridgeWorkspaceFileRevertResult,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileRevertUndoRequest {
    pub transaction_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceImageRequest {
    pub source: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceImageResponse {
    pub image: BridgeWorkspaceImageView,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceImageView {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mime: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub open_href: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size: Option<u64>,
    pub url: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceListResponse {
    pub entries: Vec<BridgeWorkspaceEntry>,
    pub path: String,
    pub protocol_version: u64,
    pub truncated: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceRequest {
    pub path: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceTargetResponse {
    pub protocol_version: u64,
    pub session_id: String,
    pub workspace_root: String,
}
