// Code generated by cmd/desktop-bridge-protocol-gen from docs/tauri/protocol/v1.schema.json. DO NOT EDIT.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeAnswerQuestionRequest {
    pub answers: Vec<BridgeAskAnswer>,
    pub id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeApprovalRequest {
    pub allow: bool,
    pub id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeAskAnswer {
    pub question_id: String,
    pub selected: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeAttachFileRequest {
    pub path: String,
    pub session_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeAttachment {
    pub is_image: bool,
    pub name: String,
    pub path: String,
    pub size: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeAttachmentResponse {
    pub attachment: BridgeAttachment,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeCodeRewindCommitRequest {
    pub confirm_partial_coverage: bool,
    pub plan_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeCodeRewindPlanResponse {
    pub plan: BridgeWorkspaceCodeRewindPlan,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeCodeRewindPreviewRequest {
    pub turn: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeCombinedRewindCommitRequest {
    pub confirm_partial_coverage: bool,
    pub plan_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeCombinedRewindPlanResponse {
    pub plan: BridgeWorkspaceCombinedRewindPlan,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeCombinedRewindPreviewRequest {
    pub turn: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeCombinedRewindResultResponse {
    pub protocol_version: u64,
    pub result: BridgeWorkspaceCombinedRewindResult,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeConversationRewindCommitRequest {
    pub plan_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeConversationRewindPlanResponse {
    pub plan: BridgeWorkspaceConversationRewindPlan,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeConversationRewindPreviewRequest {
    pub turn: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeConversationRewindResultResponse {
    pub protocol_version: u64,
    pub result: BridgeWorkspaceConversationRewindResult,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeConversationRewindUndoRequest {
    pub head_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeDeleteSessionResponse {
    pub deleted: bool,
    pub protocol_version: u64,
    pub session_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeError {
    pub error: BridgeErrorBody,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeErrorBody {
    pub code: String,
    pub message: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeEvent {
    pub event_kind: String,
    pub payload: Value,
    pub protocol_version: u64,
    pub sequence: u64,
    pub session_id: String,
    pub tab_id: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeHealth {
    pub capabilities: Vec<String>,
    pub protocol_version: u64,
    pub sidecar_instance_id: String,
    pub status: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeHistoryMessage {
    pub content: String,
    pub created_at_ms: Option<u64>,
    pub role: String,
    pub truncated: Option<bool>,
    pub turn_usage: Option<BridgeHistoryTurnUsage>,
    pub work_duration_ms: Option<u64>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeHistoryResponse {
    pub messages: Vec<BridgeHistoryMessage>,
    pub protocol_version: u64,
    pub sequence: u64,
    pub session: BridgeSession,
    pub start_index: u64,
    pub total_messages: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeHistoryTurnUsage {
    pub cache_hit_tokens: Option<u64>,
    pub cache_miss_tokens: Option<u64>,
    pub complete: bool,
    pub estimated: bool,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub reasoning_tokens: u64,
    pub request_count: u64,
    pub total_tokens: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeLegacyConversationForkResult {
    pub error: Option<String>,
    pub ok: bool,
    pub session_id: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeLegacyConversationForkResultResponse {
    pub protocol_version: u64,
    pub result: BridgeLegacyConversationForkResult,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeMCPInteractionAnswerRequest {
    pub action: String,
    pub content: Option<Value>,
    pub id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeOpenSessionRequest {
    pub session_id: String,
    pub workspace_root: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeProjectFolder {
    pub root: String,
    pub title: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeProjectFoldersResponse {
    pub projects: Vec<BridgeProjectFolder>,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeProviderModelProbeRequest {
    pub api_key: Option<String>,
    pub model: String,
    pub name: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeProviderModelProbeResponse {
    pub latency_millis: u64,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeProviderSummary {
    pub configured: bool,
    pub display_name: Option<String>,
    pub kind: String,
    pub model_count: u64,
    pub models: Vec<String>,
    pub name: String,
    pub requires_key: bool,
    pub search_models: Vec<String>,
    pub vision_models: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeProviderSummaryResponse {
    pub compact_ratio_percent: f64,
    pub default_model: String,
    pub planner_model: String,
    pub protocol_version: u64,
    pub providers: Vec<BridgeProviderSummary>,
    pub reasoning_language: String,
    pub scope: String,
    pub vision_model: String,
    pub web_search_model: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteBrowseEntry {
    pub is_dir: bool,
    pub mod_time: u64,
    pub name: String,
    pub path: String,
    pub size: u64,
    pub symlink: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteBrowseRequest {
    pub name: String,
    pub path: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteBrowseResponse {
    pub entries: Vec<BridgeRemoteBrowseEntry>,
    pub parent_path: String,
    pub path: String,
    pub protocol_version: u64,
    pub truncated: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteConnectRequest {
    pub name: String,
    pub passphrase: Option<String>,
    pub password: Option<String>,
    pub trust_fingerprint: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteConnectResponse {
    pub address: Option<String>,
    pub fingerprint: Option<String>,
    pub host: Option<String>,
    pub key_type: Option<String>,
    pub message: Option<String>,
    pub protocol_version: u64,
    pub status: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteDisconnectRequest {
    pub name: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteDisconnectResponse {
    pub disconnected: bool,
    pub name: String,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteFilePreviewRequest {
    pub name: String,
    pub path: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteFilePreviewResponse {
    pub content: String,
    pub kind: String,
    pub path: String,
    pub protocol_version: u64,
    pub revision: String,
    pub truncated: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteFileSaveRequest {
    pub content: String,
    pub name: String,
    pub path: String,
    pub revision: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRemoteFileSaveResponse {
    pub path: String,
    pub protocol_version: u64,
    pub revision: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeRenameSessionRequest {
    pub title: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSession {
    pub id: String,
    pub model_ref: Option<String>,
    pub path: String,
    pub state: String,
    pub title: Option<String>,
    pub workspace_root: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSessionHeadSwitchRequest {
    pub head_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSessionHeadSwitchResponse {
    pub ok: bool,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSessionHeadView {
    pub id: String,
    pub kind: String,
    pub message_count: u64,
    pub name: Option<String>,
    pub parent_id: Option<String>,
    pub preview: Option<String>,
    pub selected: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSessionHeadsResponse {
    pub heads: Vec<BridgeSessionHeadView>,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSessionMetrics {
    pub cache_hit_tokens: u64,
    pub cache_miss_tokens: u64,
    pub compact_threshold_percent: u64,
    pub context_used_tokens: u64,
    pub context_window_tokens: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSessionResponse {
    pub metrics: Option<BridgeSessionMetrics>,
    pub protocol_version: u64,
    pub sequence: Option<u64>,
    pub session: BridgeSession,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSetAgentPreferenceRequest {
    pub compact_ratio_percent: Option<f64>,
    pub reasoning_language: Option<String>,
    pub scope: Option<String>,
    pub workspace_root: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSetDefaultModelRequest {
    pub model: String,
    pub scope: Option<String>,
    pub workspace_root: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSetModelRoleRequest {
    pub model: String,
    pub role: String,
    pub scope: Option<String>,
    pub workspace_root: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSetSessionModelRequest {
    pub model: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeSubmitRequest {
    pub input: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceChangeDetail {
    pub added: Option<u64>,
    pub binary: Option<bool>,
    pub diff: Option<String>,
    pub removed: Option<u64>,
    pub source: Option<String>,
    pub truncated: Option<bool>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceChangeDetailRequest {
    pub path: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceChangeDetailResponse {
    pub detail: BridgeWorkspaceChangeDetail,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceChangeView {
    pub can_session_revert: Option<bool>,
    pub git_status: Option<String>,
    pub latest_prompt: Option<String>,
    pub latest_time: Option<u64>,
    pub old_path: Option<String>,
    pub path: String,
    pub sources: Vec<String>,
    pub turns: Option<Vec<u64>>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceChanges {
    pub files: Vec<BridgeWorkspaceChangeView>,
    pub git_available: bool,
    pub git_branch: Option<String>,
    pub git_err: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceChangesResponse {
    pub changes: BridgeWorkspaceChanges,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceCheckpointView {
    pub prompt: String,
    pub time: u64,
    pub turn: u64,
    pub turn_file_count: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceCheckpointsResponse {
    pub checkpoints: Vec<BridgeWorkspaceCheckpointView>,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceCodeRewindPlan {
    pub can_files: bool,
    pub conflicts: Vec<String>,
    pub coverage: String,
    pub coverage_gaps: Vec<String>,
    pub disabled_reason: Option<String>,
    pub file_count: u64,
    pub files: Vec<String>,
    pub files_truncated: bool,
    pub plan_id: Option<String>,
    pub requires_coverage_confirmation: bool,
    pub turn: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceCombinedRewindPlan {
    pub can_conversation: bool,
    pub can_files: bool,
    pub conflicts: Vec<String>,
    pub coverage_gaps: Vec<String>,
    pub disabled_reason: Option<String>,
    pub file_count: u64,
    pub files: Vec<String>,
    pub files_truncated: bool,
    pub plan_id: Option<String>,
    pub requires_coverage_confirmation: bool,
    pub turn: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceCombinedRewindResult {
    pub conflicts: Vec<String>,
    pub conversation_forked: bool,
    pub deleted_count: u64,
    pub error: Option<String>,
    pub files_restored: bool,
    pub head_id: Option<String>,
    pub ok: bool,
    pub partial: bool,
    pub transaction_id: Option<String>,
    pub undo_available: bool,
    pub written_count: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceConversationRewindPlan {
    pub can_conversation: bool,
    pub disabled_reason: Option<String>,
    pub plan_id: Option<String>,
    pub turn: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceConversationRewindResult {
    pub conversation_forked: bool,
    pub error: Option<String>,
    pub head_id: Option<String>,
    pub ok: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceEntry {
    pub is_dir: bool,
    pub name: String,
    pub path: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFilePreview {
    pub binary: Option<bool>,
    pub body: Option<String>,
    pub error: Option<String>,
    pub path: String,
    pub size: u64,
    pub truncated: Option<bool>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileRequest {
    pub path: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileResponse {
    pub preview: BridgeWorkspaceFilePreview,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileRevertCommitRequest {
    pub plan_id: String,
    pub resolution: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileRevertPlan {
    pub can_files: bool,
    pub conflicts: Option<Vec<String>>,
    pub disabled_reason: Option<String>,
    pub legacy: Option<bool>,
    pub path: String,
    pub plan_id: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileRevertPlanResponse {
    pub plan: BridgeWorkspaceFileRevertPlan,
    pub protocol_version: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileRevertResult {
    pub conflicts: Option<Vec<String>>,
    pub deleted_count: u64,
    pub error: Option<String>,
    pub ok: bool,
    pub transaction_id: Option<String>,
    pub undo_available: bool,
    pub written_count: u64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileRevertResultResponse {
    pub protocol_version: u64,
    pub result: BridgeWorkspaceFileRevertResult,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceFileRevertUndoRequest {
    pub transaction_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceListResponse {
    pub entries: Vec<BridgeWorkspaceEntry>,
    pub path: String,
    pub protocol_version: u64,
    pub truncated: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceRequest {
    pub path: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BridgeWorkspaceTargetResponse {
    pub protocol_version: u64,
    pub session_id: String,
    pub workspace_root: String,
}
