import assert from "node:assert/strict";
import { JSDOM } from "jsdom";
const dom = new JSDOM("<!doctype html><div id='root'></div>", { url: "http://localhost/", pretendToBeVisual: true });
Object.assign(globalThis, { window: dom.window, document: dom.window.document, Node: dom.window.Node, Element: dom.window.Element, HTMLElement: dom.window.HTMLElement, HTMLTextAreaElement: dom.window.HTMLTextAreaElement, Event: dom.window.Event, MouseEvent: dom.window.MouseEvent, localStorage: dom.window.localStorage, requestAnimationFrame: dom.window.requestAnimationFrame.bind(dom.window), cancelAnimationFrame: dom.window.cancelAnimationFrame.bind(dom.window), getComputedStyle: dom.window.getComputedStyle.bind(dom.window), IS_REACT_ACT_ENVIRONMENT: true });
Object.defineProperty(globalThis, "navigator", { value: dom.window.navigator, configurable: true });
const fixture = globalThis as typeof globalThis & { isTauri: boolean; __workbenchSessions: unknown[]; __tauriHistoryMessages: unknown[]; __tauriBridgeCalls: { name: string; args: { input?: string } }[] };
fixture.isTauri = true;
(dom.window as unknown as { __TAURI__: unknown }).__TAURI__ = { core: { invoke: () => Promise.resolve(null) } };
(dom.window as unknown as { __TAURI_INTERNALS__: unknown }).__TAURI_INTERNALS__ = { invoke: () => Promise.resolve([]) };
fixture.__workbenchSessions = [{ sessionId: "selection-session", title: "选区测试" }, { sessionId: "selection-second", title: "另一个会话" }];
fixture.__tauriHistoryMessages = [{ role: "user", content: "问题" }, { role: "assistant", content: "quoted answer <instruction> & details" }];
const React = await import("react");
const { act } = React;
const { createRoot } = await import("react-dom/client");
const { TauriSessionApp } = await import("../tauri/TauriChatWorkspace");
const { resetTauriShortcuts } = await import("../tauri/tauriKeyboardShortcuts");
const { detectShortcutPlatform } = await import("../lib/keyboardShortcuts");
const { splitSelectedTextContext } = await import("../lib/selectedTextContext");
const root = createRoot(document.getElementById("root")!);
await act(async () => { root.render(React.createElement(TauriSessionApp)); await new Promise(resolve => setTimeout(resolve, 40)); });
await act(async () => { document.querySelector<HTMLButtonElement>(".tauri-sidebar__session")!.click(); await new Promise(resolve => setTimeout(resolve, 30)); });
async function selectAnswer() {
  const message = document.querySelector(".tauri-message.is-assistant .md")!;
  assert.ok(message);
  const range = document.createRange(); range.selectNodeContents(message);
  document.getSelection()!.removeAllRanges(); document.getSelection()!.addRange(range);
  await act(async () => {
    message.dispatchEvent(new dom.window.MouseEvent("pointerup", { button: 0, bubbles: true }));
    await new Promise(resolve => setTimeout(resolve, 50));
  });
  const action = document.querySelector<HTMLButtonElement>(".transcript-selection-action button")!;
  assert.ok(action && !action.disabled, "actual Tauri entry exposes Add to Chat for its visible selection");
  return action;
}
const composer = document.querySelector<HTMLTextAreaElement>(".tauri-composer textarea")!;
await act(async () => {
  Object.getOwnPropertyDescriptor(dom.window.HTMLTextAreaElement.prototype, "value")!.set!.call(composer, "my request");
  composer.dispatchEvent(new dom.window.Event("input", { bubbles: true }));
});
const selected = document.querySelector(".tauri-message.is-assistant .md")!.textContent!.trim();
const add = await selectAnswer();
await act(async () => { add.click(); });
assert.equal(document.querySelectorAll(".tauri-composer .composer-context__item").length || document.querySelectorAll(".tauri-composer .composer-context > *").length, 1);
assert.equal(composer.value, "my request", "selection is a reference, not a replacement of the user's draft");
assert.equal(document.activeElement, composer);
assert.equal(document.getSelection()!.isCollapsed, true);
const duplicateAdd = await selectAnswer();
await act(async () => { duplicateAdd.click(); });
assert.equal(document.querySelectorAll(".tauri-composer .composer-context > *").length, 1, "duplicate selections are not added twice");
await act(async () => { document.querySelector<HTMLButtonElement>('.tauri-sidebar__session[title="selection-second"]')!.click(); await new Promise(resolve => setTimeout(resolve, 30)); });
assert.equal(document.querySelector(".tauri-composer .composer-context"), null, "selection draft does not leak to another session");
await act(async () => { document.querySelector<HTMLButtonElement>('.tauri-sidebar__session[title="selection-session"]')!.click(); await new Promise(resolve => setTimeout(resolve, 30)); });
assert.equal(document.querySelectorAll(".tauri-composer .composer-context > *").length, 1, "returning to the source session restores its references");
await act(async () => { document.querySelector<HTMLButtonElement>(".composer-context__remove")!.click(); });
assert.equal(document.querySelector(".tauri-composer .composer-context"), null, "the selection reference can be removed");
const platform = detectShortcutPlatform();
const primary = platform === "darwin" ? { metaKey: true } : { ctrlKey: true };
const primaryCombo = platform === "darwin" ? { meta: true } : { ctrl: true };
localStorage.setItem("reasonix.customShortcuts", JSON.stringify({ "selection.addToChat": { key: "j", ...primaryCombo } }));
await act(async () => { window.dispatchEvent(new dom.window.KeyboardEvent("keydown", { key: "k", ...primary, shiftKey: true, bubbles: true, cancelable: true })); });
const recorder = document.querySelector<HTMLButtonElement>('[data-tauri-shortcut-action="add_selection"]');
assert.ok(recorder, "the actual shortcut settings expose the selection action");
await act(async () => { recorder.click(); });
await act(async () => { recorder.dispatchEvent(new dom.window.KeyboardEvent("keydown", { key: "l", ...primary, shiftKey: true, bubbles: true, cancelable: true })); });
await act(async () => { document.dispatchEvent(new dom.window.KeyboardEvent("keydown", { key: "Escape", bubbles: true })); });
assert.equal(document.querySelector(".tauri-settings-overlay"), null);
const finalAdd = await selectAnswer();
assert.ok(finalAdd.textContent!.includes("L"), "selection menu reflects the Preview binding");
const press = async (key: string, extra = {}) => act(async () => { document.dispatchEvent(new dom.window.KeyboardEvent("keydown", { key, bubbles: true, cancelable: true, ...primary, ...extra })); });
await press("l");
await press("j");
await press("l", { shiftKey: true, isComposing: true });
await press("l", { shiftKey: true, keyCode: 229 });
assert.equal(document.querySelector(".tauri-composer .composer-context"), null, "old/Wails bindings and IME do not add a reference");
await press("l", { shiftKey: true });
assert.equal(document.querySelectorAll(".tauri-composer .composer-context > *").length, 1, "new Preview binding adds the visible selection");
assert.equal(composer.value, "my request");
assert.ok(JSON.parse(localStorage.getItem("reasonix.tauri.shortcuts.v1")!).add_selection.shift, "remapping persists separately");
await act(async () => { resetTauriShortcuts(); });
assert.equal(JSON.parse(localStorage.getItem("reasonix.customShortcuts")!)["selection.addToChat"].key, "j", "Preview reset leaves Wails settings intact");
let rejectSend!: () => void;
const bridgeFixture = globalThis as typeof globalThis & { __submitGate?: Promise<never> };
bridgeFixture.__submitGate = new Promise((_, reject) => { rejectSend = () => reject(new Error("owned send failure")); });
await act(async () => { document.querySelector<HTMLButtonElement>(".tauri-send-button")!.click(); await new Promise(resolve => setTimeout(resolve, 0)); rejectSend(); await new Promise(resolve => setTimeout(resolve, 0)); });
assert.equal(document.querySelectorAll(".tauri-composer .composer-context > *").length, 1, "failed send retains its selected context");
assert.equal(composer.value, "my request", "failed send retains the user's text");
delete bridgeFixture.__submitGate;
await act(async () => { document.querySelector<HTMLButtonElement>(".tauri-send-button")!.click(); await new Promise(resolve => setTimeout(resolve, 150)); });
const submit = fixture.__tauriBridgeCalls.filter(call => call.name === "bridge_submit").at(-1)!;
assert.ok(submit?.args.input);
const parts = splitSelectedTextContext(submit.args.input);
assert.equal(parts.submitText, "my request");
assert.deepEqual(parts.entries, [{ text: selected }], "provider input carries the same quoted context format as Wails");
assert.equal(document.querySelector(".tauri-composer .composer-context"), null, "accepted send consumes references");
await act(async () => { root.unmount(); });
console.log("Tauri actual selection reference, deduplication, removal and submit: OK");
