// Feature-local copy stays in the lazy Tauri settings chunk.
import type { Locale } from "../lib/i18n";

const en = {
  "width": "Conversation width",
  "textSize": "Text size",
  "font": "Body font",
  "customFont": "Custom body font",
  "monoFont": "Monospace font",
  "customMonoFont": "Custom monospace font",
  "theme": "Appearance cache",
  "themeStyle": "Style cache",
  "title": "Old Preview UI preferences",
  "hint": "Old UI preferences were shared across profiles. Review the workspace and values before importing into this profile. Import replaces the listed UI preferences and preserves the source. Configuration, sessions and credentials use their own migration tools. Appearance caches follow the appearance settings saved in the current profile.",
  "preview": "Preview old UI preferences",
  "empty": "No old UI preferences were found.",
  "confirm": "I reviewed the old workspace and preferences and confirm importing them into this profile.",
  "import": "Import with rollback record",
  "imported": "Imported {count} UI preferences. Restart the app to apply them.",
  "rollbackHint": "This profile has a rollback record. Undo restores preferences that still match the imported values and preserves later edits.",
  "rollback": "Undo UI preference migration",
  "restored": "Restored {restored} UI preferences. Restart the app to apply them.",
  "conflicts": "Restored {restored} preferences; preserved {conflicts} later edits. The rollback record remains. Review the edited preferences before retrying.",
  "workspace": "Default workspace",
  "shortcuts": "Keyboard shortcuts",
  "layout": "Desktop layout",
  "statusBar": "Status bar",
  "projects": "Project expansion",
  "notifications": "Desktop notifications",
  "notificationEvents": "Notification events",
  "progress": "Progress display",
  "sidebar": "Sidebar visibility",
  "typography": "Region typography",
  "successSound": "Completion sound",
  "attentionSound": "Attention sound",
  "volume": "Notification volume",
  "music": "Ambient music"
} as const;
export type UiMigrationKey = keyof typeof en;
const dictionaries: Record<Locale, Record<UiMigrationKey, string>> = {
  en,
  "zh": {
  "width": "对话宽度",
  "textSize": "文字大小",
  "font": "正文字体",
  "customFont": "自定义正文字体",
  "monoFont": "等宽字体",
  "customMonoFont": "自定义等宽字体",
  "theme": "外观缓存",
  "themeStyle": "样式缓存",
  "title": "旧 Preview 界面偏好",
  "hint": "旧界面偏好由多个档案共享。先核对旧工作区和偏好，再确认迁入当前档案。导入会覆盖对应界面偏好，原记录保留；配置、会话和系统凭据沿用各自的迁移入口。 外观缓存仍服从当前档案已保存的外观设置。",
  "preview": "预览旧界面偏好",
  "empty": "未发现可迁移的旧界面偏好。",
  "confirm": "我已核对旧工作区和偏好，确认迁入当前档案。",
  "import": "导入并保留回退记录",
  "imported": "已导入 {count} 项界面偏好，重启应用后生效。",
  "rollbackHint": "当前档案已保留此次迁移的原偏好。撤回会恢复仍与导入值一致的偏好；迁移后的新修改会保留。",
  "rollback": "撤回界面偏好迁移",
  "restored": "已恢复 {restored} 项界面偏好，重启应用后生效。",
  "conflicts": "已恢复 {restored} 项，另有 {conflicts} 项后续修改已保留。回退记录仍保留，请核对这些偏好后重试。",
  "workspace": "默认工作区",
  "shortcuts": "快捷键",
  "layout": "桌面布局",
  "statusBar": "状态栏",
  "projects": "项目折叠状态",
  "notifications": "桌面通知",
  "notificationEvents": "通知事件",
  "progress": "进度显示",
  "sidebar": "侧栏显示",
  "typography": "分区排版",
  "successSound": "完成音效",
  "attentionSound": "提醒音效",
  "volume": "通知音量",
  "music": "环境音乐"
},
  "zh-TW": {
  "width": "對話寬度",
  "textSize": "文字大小",
  "font": "正文字型",
  "customFont": "自訂正文字型",
  "monoFont": "等寬字型",
  "customMonoFont": "自訂等寬字型",
  "theme": "外觀快取",
  "themeStyle": "樣式快取",
  "title": "舊 Preview 介面偏好",
  "hint": "舊介面偏好由多個檔案共用。先核對舊工作區及偏好，再確認遷入目前檔案。匯入會覆蓋對應介面偏好，原記錄保留；設定、對話及系統憑證沿用各自的遷移入口。 外觀快取仍依照目前檔案已儲存的外觀設定。",
  "preview": "預覽舊介面偏好",
  "empty": "未發現可遷移的舊介面偏好。",
  "confirm": "我已核對舊工作區及偏好，確認遷入目前檔案。",
  "import": "匯入並保留回退記錄",
  "imported": "已匯入 {count} 項介面偏好，重新啟動應用程式後生效。",
  "rollbackHint": "目前檔案已保留此次遷移的原偏好。撤回會還原仍與匯入值一致的偏好；遷移後的新修改會保留。",
  "rollback": "撤回介面偏好遷移",
  "restored": "已還原 {restored} 項介面偏好，重新啟動應用程式後生效。",
  "conflicts": "已還原 {restored} 項，另有 {conflicts} 項後續修改已保留。回退記錄仍保留，請核對這些偏好後重試。",
  "workspace": "預設工作區",
  "shortcuts": "快捷鍵",
  "layout": "桌面配置",
  "statusBar": "狀態列",
  "projects": "專案展開狀態",
  "notifications": "桌面通知",
  "notificationEvents": "通知事件",
  "progress": "進度顯示",
  "sidebar": "側欄顯示",
  "typography": "區域排版",
  "successSound": "完成音效",
  "attentionSound": "提醒音效",
  "volume": "通知音量",
  "music": "環境音樂"
},
};
export function translateUiMigration(locale: Locale, key: UiMigrationKey, vars?: Record<string, string | number>): string {
  return dictionaries[locale][key].replace(/\{(\w+)\}/g, (match, name: string) => vars?.[name] === undefined ? match : String(vars[name]));
}
