import assert from "node:assert/strict";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";
const dom = new JSDOM("<!doctype html><html><body><div id='root'></div></body></html>", { url: "http://localhost/", pretendToBeVisual: true });
Object.assign(globalThis, { window: dom.window, document: dom.window.document, Element: dom.window.Element, HTMLElement: dom.window.HTMLElement, SVGElement: dom.window.SVGElement, DOMParser: dom.window.DOMParser, XMLSerializer: dom.window.XMLSerializer, MutationObserver: dom.window.MutationObserver, localStorage: dom.window.localStorage, IS_REACT_ACT_ENVIRONMENT: true, isTauri: true });
Object.defineProperty(globalThis, "navigator", { value: dom.window.navigator, configurable: true });
Object.defineProperty(window, "matchMedia", { value: () => ({ matches: false, addEventListener() {}, removeEventListener() {} }) });
let denied = false, fallbackCalls = 0, copied = "";
const commands: string[] = [];
window.open = () => { fallbackCalls++; return null; };
Object.defineProperty(navigator, "clipboard", { value: { writeText: async () => { fallbackCalls++; } } });
(window as unknown as { __TAURI_INTERNALS__: unknown }).__TAURI_INTERNALS__ = { invoke: async (command: string, args: { url?: string; text?: string }) => {
  commands.push(command);
  if (denied) throw new Error("native refusal with private details");
  if (command === "plugin:clipboard-manager|write_text") copied = args.text ?? "";
  else { assert.equal(command, "open_external_link"); assert.equal(args.url, "https://example.com/diagram"); }
} };
const { default: MermaidDiagram, __setMermaidRenderAdapterForTest, __setMermaidPanZoomFactoryForTest } = await import("../components/MermaidDiagram");
const { LocaleProvider, t } = await import("../lib/i18n");
const { ToastProvider } = await import("../lib/toast");
__setMermaidPanZoomFactoryForTest(null);
__setMermaidRenderAdapterForTest(async () => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><a id="external" href="https://example.com/diagram"><text>Docs</text></a><a id="internal" href="#node"><text>Node</text></a><a id="unsafe" href="javascript:alert(1)"><text>Unsafe</text></a></svg>');
const root = createRoot(document.getElementById("root")!);
await act(async () => root.render(<LocaleProvider><ToastProvider><MermaidDiagram definition="graph TD; A-->B" /></ToastProvider></LocaleProvider>));
for (let n = 0; n < 30 && !document.querySelector("#external"); n++) await act(async () => { await new Promise(resolve => setTimeout(resolve, 0)); });
const anchor = document.querySelector("#external")!;
assert.ok(anchor);
await act(async () => { anchor.dispatchEvent(new dom.window.MouseEvent("auxclick", { bubbles: true, cancelable: true, button: 2 })); });
assert.equal(commands.length, 0, "right mouse release does not open an external diagram link");
for (const event of [new dom.window.MouseEvent("click", { bubbles: true, cancelable: true }), new dom.window.MouseEvent("auxclick", { bubbles: true, cancelable: true, button: 1 })]) {
  await act(async () => { anchor.dispatchEvent(event); });
  assert.equal(event.defaultPrevented, true);
  assert.equal(commands.at(-1), "open_external_link");
}
const count = commands.length;
for (const id of ["internal", "unsafe"]) await act(async () => { document.querySelector(`#${id}`)!.dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true, cancelable: true })); });
assert.equal(commands.length, count, "fragments and stripped unsafe URLs never reach the opener");
denied = true;
await act(async () => { anchor.dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true, cancelable: true })); });
assert.ok(document.body.textContent?.includes(t("settings.about.openLinkFailed")));
assert.equal(anchor.isConnected, true, "failure feedback preserves the live diagram DOM");
const recovery = document.querySelector<HTMLButtonElement>(".toast__action")!;
assert.ok(recovery);
denied = false;
await act(async () => recovery.click());
assert.equal(copied, "https://example.com/diagram");
assert.ok(document.body.textContent?.includes(t("richLink.copied")));
denied = true;
await act(async () => { document.querySelector("#external")!.dispatchEvent(new dom.window.MouseEvent("click", { bubbles: true, cancelable: true })); });
await act(async () => document.querySelector<HTMLButtonElement>(".toast__action")!.click());
assert.ok(document.body.textContent?.includes(t("richLink.copyFailed")));
assert.equal(fallbackCalls, 0);
assert.ok(!document.body.textContent?.includes("private details"));
await act(async () => root.unmount());
__setMermaidRenderAdapterForTest(null);
__setMermaidPanZoomFactoryForTest(undefined);
dom.window.close();
console.log("Mermaid native links: mouse ownership, refusal/copy recovery and protocol boundary OK");
