import assert from "node:assert/strict";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";
const dom = new JSDOM("<!doctype html><html><body><div id='root'></div></body></html>", { url: "http://localhost/" });
Object.assign(globalThis, { window: dom.window, document: dom.window.document, HTMLElement: dom.window.HTMLElement, localStorage: dom.window.localStorage, IS_REACT_ACT_ENVIRONMENT: true, isTauri: true });
Object.defineProperty(globalThis, "navigator", { value: dom.window.navigator, configurable: true });
let browserCalls = 0;
Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: async () => { browserCalls++; throw new Error("WebView denied"); }, readText: async () => { browserCalls++; throw new Error("WebView denied"); } } });
Object.defineProperty(document, "execCommand", { value: () => false, configurable: true });
let clipboard = "", denied = false, deferRead = false;
let delayedRead: ((value: string) => void) | undefined;
const calls: string[] = [];
(window as unknown as { __TAURI_INTERNALS__: unknown }).__TAURI_INTERNALS__ = { invoke: async (command: string, args?: { text?: string; scope?: string; workspaceRoot?: string }) => {
  calls.push(command);
  if (command === "hooks_settings") return { protocolVersion: 1, scope: args?.scope ?? "global", path: "/private/settings.json", revision: "r1", events: ["Stop"], hooks: args?.workspaceRoot ? { Stop: [{ command: "new workspace" }] } : {} };
  if (command === "plugin_settings") return { protocolVersion: 1, plugins: [] };
  if (command.startsWith("plugin:clipboard-manager|")) {
    if (denied) throw new Error("native busy");
    if (command.endsWith("write_text")) { clipboard = args?.text ?? ""; return; }
    if (deferRead) return new Promise<string>(resolve => { delayedRead = resolve; });
    return clipboard;
  }
  throw new Error(`unexpected command: ${command}`);
} };
const { TauriHooksSettings } = await import("../tauri/TauriHooksSettings");
const { LocaleProvider, t } = await import("../lib/i18n");
const root = createRoot(document.getElementById("root")!);
const render = async (workspaceRoot = "") => { await act(async () => { root.render(<LocaleProvider><TauriHooksSettings workspaceRoot={workspaceRoot} /></LocaleProvider>); }); };
const editor = () => document.querySelector<HTMLTextAreaElement>(".tauri-hooks-editor")!;
const click = async (key: "copy" | "paste") => { await act(async () => { const button = [...document.querySelectorAll<HTMLButtonElement>(".tauri-hooks-toolbar button")].find(button => button.textContent === t(`settings.hooks.${key}`)); assert.ok(button); button.click(); }); };
await render();
const initial = editor().value;
await click("copy");
assert.equal(clipboard, initial, "JSON copy uses native text IPC");
assert.ok(document.body.textContent?.includes(t("settings.hooks.jsonCopied")));
assert.equal(browserCalls, 0, "native JSON copy does not require WebView clipboard permission");
clipboard = '{"hooks":{"Stop":[{"command":"draft"}]}}';
await click("paste");
assert.equal(editor().value, clipboard, "native JSON paste reaches the editor");
const draft = editor().value;
denied = true;
await click("paste");
assert.equal(editor().value, draft, "read refusal preserves the unsaved draft");
assert.ok(document.body.textContent?.includes(t("settings.hooks.pasteFailed")));
await click("copy");
assert.ok(document.body.textContent?.includes(t("settings.hooks.copyFailed")));
assert.ok(!document.body.textContent?.includes(t("settings.hooks.jsonCopied")), "a failed copy clears previous success");
denied = false; clipboard = "";
await click("paste");
assert.equal(editor().value, draft, "empty clipboard preserves the draft");
deferRead = true;
await click("paste");
assert.equal(editor().disabled, true, "pending native paste prevents conflicting editing");
assert.ok(delayedRead);
await render("/new workspace");
const nextDraft = editor().value;
assert.ok(nextDraft.includes("new workspace"));
await act(async () => { delayedRead!("stale clipboard result"); });
assert.equal(editor().value, nextDraft, "previous-workspace paste cannot overwrite the new context");
assert.equal(editor().disabled, false);
assert.ok(!calls.includes("change_hooks_settings"), "clipboard operations never persist or execute hook commands");
await act(async () => { root.unmount(); });
console.log("Hooks native JSON clipboard, denial/empty draft protection and stale workspace completion: OK");
