import assert from "node:assert/strict";
import { JSDOM } from "jsdom";
const dom = new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>', { url: "http://localhost", pretendToBeVisual: true });
Object.assign(globalThis, { window: dom.window, document: dom.window.document, Node: dom.window.Node, HTMLElement: dom.window.HTMLElement, localStorage: dom.window.localStorage, IS_REACT_ACT_ENVIRONMENT: true });
Object.defineProperty(globalThis, "navigator", { value: dom.window.navigator, configurable: true });
localStorage.setItem("locale", "zh");
let copied = "";
(dom.window as unknown as { __TAURI_INTERNALS__: unknown }).__TAURI_INTERNALS__ = { invoke: async (_: string, args: { text?: string }) => { copied = args.text ?? ""; } };
(globalThis as unknown as { isTauri: boolean }).isTauri = true;
const React = await import("react"); const { act } = React;
const { createRoot } = await import("react-dom/client");
const { LocaleProvider } = await import("../lib/i18n"); const { ToastProvider } = await import("../lib/toast");
const { TauriAnswerActions } = await import("../tauri/TauriAnswerActions");
const root = createRoot(document.getElementById("root")!);
const usage = { inputTokens: 1800000, outputTokens: 100000, totalTokens: 1900000, requestCount: 4, reasoningTokens: 40000, cacheHitTokens: 1500000, cacheMissTokens: 300000, complete: true, estimated: false };
const render = async (value = usage) => act(async () => { root.render(<LocaleProvider><ToastProvider><TauriAnswerActions text="完整回答 **原文**" createdAtMs={new Date(2026, 9, 4, 22, 17).getTime()} usage={value} /></ToastProvider></LocaleProvider>); });
await render();
const button = () => document.querySelector<HTMLButtonElement>('.tauri-answer-actions__usage')!;
assert.match(button().textContent!, /1.9M tok/); assert.equal(button().getAttribute("aria-expanded"), "false");
await act(async () => button().click());
let panel = document.querySelector<HTMLElement>('[role="dialog"]')!;
assert.ok(panel); assert.equal(button().getAttribute('aria-controls'), panel.id); assert.match(panel.textContent!, /1,900,000/); assert.match(panel.textContent!, /1,500,000/);
assert.equal(document.activeElement, panel.querySelector('button'));
await act(async () => document.dispatchEvent(new dom.window.KeyboardEvent('keydown', {key: 'Escape', bubbles: true, cancelable: true})));
assert.equal(document.querySelector('[role="dialog"]'), null); assert.equal(document.activeElement, button());
await act(async () => document.querySelector<HTMLButtonElement>('.tauri-answer-actions .copybtn')!.click());
assert.equal(copied, "完整回答 **原文**"); assert.match(document.querySelector('.copybtn')!.getAttribute('aria-label')!, /已复制|Copied/);
await render({ ...usage, cacheHitTokens: undefined, cacheMissTokens: undefined, complete: false, estimated: true } as unknown as typeof usage);
assert.match(button().textContent!, /约|≈/);
await act(async () => button().click()); panel = document.querySelector('[role="dialog"]')!;
assert.match(panel.textContent!, /部分请求|partial/); assert.match(panel.textContent!, /估算|estimated/); assert.doesNotMatch(panel.textContent!, /缓存命中|Cached input/);
await act(async () => window.dispatchEvent(new dom.window.Event('resize'))); assert.equal(document.querySelector('[role="dialog"]'), null);
await act(async () => root.render(<LocaleProvider><ToastProvider><TauriAnswerActions text="旧回答" /></ToastProvider></LocaleProvider>));
assert.equal(document.querySelector('time'), null); assert.equal(document.querySelector('.tauri-answer-actions__usage'), null); assert.match(document.body.textContent!, /用量未记录|Usage not recorded/);
await act(async () => root.unmount()); dom.window.close();
console.log('Tauri answer copy/time/turn usage, missing data and dialog focus: OK');
