import assert from "node:assert/strict";
import { JSDOM } from "jsdom";

const dom = new JSDOM("<!doctype html><html><body><div id='root'></div></body></html>", { url: "http://localhost/", pretendToBeVisual: true });
Object.assign(globalThis, { window: dom.window, document: dom.window.document, HTMLElement: dom.window.HTMLElement, Event: dom.window.Event, MouseEvent: dom.window.MouseEvent, requestAnimationFrame: dom.window.requestAnimationFrame.bind(dom.window), cancelAnimationFrame: dom.window.cancelAnimationFrame.bind(dom.window), localStorage: dom.window.localStorage, IS_REACT_ACT_ENVIRONMENT: true });
Object.defineProperty(globalThis, "navigator", { value: dom.window.navigator, configurable: true });
(globalThis as typeof globalThis & { isTauri?: boolean }).isTauri = true;
(dom.window as unknown as { __TAURI_INTERNALS__?: unknown }).__TAURI_INTERNALS__ = { invoke: async () => [] };
(dom.window as unknown as { __TAURI__?: unknown }).__TAURI__ = { core: { invoke: () => Promise.resolve(null) } };
const state = globalThis as unknown as {
  __workbenchSessions: Array<{ sessionId: string; title: string; workspaceRoot?: string }>;
  __archivedSessions: Array<{ sessionId: string; title: string; archivedAtMs: number }>;
  __archiveChangeError?: string; __archiveReadError?: string;
  __tauriBridgeCalls: Array<{ name: string; args?: { sessionId?: string; archived?: boolean } }>;
};
state.__workbenchSessions = [{ sessionId: "first", title: "保留历史" }, { sessionId: "older", title: "旧归档" }];
state.__archivedSessions = [{ sessionId: "older", title: "旧归档", archivedAtMs: 1 }];
const React = await import("react");
const { act } = React;
const { createRoot } = await import("react-dom/client");
const { TauriSessionApp } = await import("../tauri/TauriChatWorkspace");
let root = createRoot(document.getElementById("root")!);
const settle = () => new Promise(resolve => setTimeout(resolve, 0));
const click = async (button: HTMLButtonElement | null) => { assert.ok(button); await act(async () => { button.click(); await settle(); await settle(); }); };
const button = (name: string) => [...document.querySelectorAll<HTMLButtonElement>("button")].find(item => item.getAttribute("aria-label") === name) ?? null;
await act(async () => { root.render(React.createElement(TauriSessionApp)); await settle(); await settle(); });
assert.equal(button("归档对话 旧归档"), null, "persisted archive must not appear in ordinary list");
await click(button("归档对话 保留历史"));
assert.ok(document.querySelector('[aria-label="确认归档对话"]'));
state.__archiveChangeError = "磁盘写入失败";
await click(document.querySelector('[aria-label="确认归档对话"] .tauri-session-delete__confirm'));
assert.equal(state.__archivedSessions.length, 1, "refused commit must not hide or publish an archive");
assert.match(document.body.textContent ?? "", /磁盘写入失败/);
delete state.__archiveChangeError;
await click(document.querySelector('[aria-label="确认归档对话"] .tauri-session-delete__confirm'));
assert.equal(state.__archivedSessions.length, 2);
assert.equal(button("归档对话 保留历史"), null, "committed archive leaves ordinary list");
assert.ok(!state.__tauriBridgeCalls.some(call => call.name === "bridge_delete_session"), "archive must never invoke permanent delete");
await act(async () => { root.unmount(); });
root = createRoot(document.getElementById("root")!);
await act(async () => { root.render(React.createElement(TauriSessionApp)); await settle(); await settle(); });
assert.equal(button("归档对话 保留历史"), null, "remount must reload persisted archive overlay");
await click([...document.querySelectorAll<HTMLButtonElement>("button")].find(item => item.classList.contains("tauri-archives-toggle")) ?? null);
assert.ok(document.querySelector('[role="dialog"][aria-label="已归档对话"]'));
const restore = document.querySelector<HTMLButtonElement>('.tauri-archives-panel article button');
await click(restore);
assert.ok(state.__tauriBridgeCalls.some(call => call.name === "bridge_change_session_archive" && call.args?.archived === false));
assert.ok(state.__tauriBridgeCalls.some(call => call.name === "bridge_switch_session" && call.args?.sessionId === "older"), "restoration reopens original ID without stale archive guard");
assert.equal(document.querySelector('[role="dialog"][aria-label="已归档对话"]'), null);
await act(async () => { root.unmount(); });
state.__archiveReadError = "归档文件损坏";
root = createRoot(document.getElementById("root")!);
await act(async () => { root.render(React.createElement(TauriSessionApp)); await settle(); await settle(); });
assert.equal(document.querySelector('.tauri-sidebar__session'), null, "archive read failure must not expose archived rows as ordinary sessions");
delete state.__archiveReadError;
await click([...document.querySelectorAll<HTMLButtonElement>("button")].find(item => item.textContent === "重试归档状态") ?? null);
assert.ok(document.querySelector('.tauri-sidebar__session'), "successful retry restores list");
await act(async () => { root.unmount(); });
dom.window.close();
console.log("Tauri session archive component: persistence, failure, restoration, no-delete and fail-closed retry passed");
