import assert from "node:assert/strict";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";

const dom = new JSDOM("<!doctype html><html><body><div id='root'></div></body></html>", { url: "http://localhost/" });
Object.assign(globalThis, { window: dom.window, document: dom.window.document, HTMLElement: dom.window.HTMLElement, localStorage: dom.window.localStorage, IS_REACT_ACT_ENVIRONMENT: true, isTauri: true });
Object.defineProperty(globalThis, "navigator", { value: dom.window.navigator, configurable: true });
let fallbackCalls = 0, writes = 0, deferred = false, denied = false, failLoad = false;
const completions: (() => void)[] = [];
let clipboard = "";
Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: async () => { fallbackCalls++; } } });
(window as unknown as { __TAURI_INTERNALS__: unknown }).__TAURI_INTERNALS__ = { invoke: async (command: string, args?: { text?: string }) => {
  if (command === "storage_settings") {
    if (failLoad) throw new Error("storage load failed");
    return { protocolVersion: 1, profilePath: "/private/profile", statePath: "/private/state", cachePath: "/private/cache", extensionsPath: "/private/extensions" };
  }
  if (command === "workspace_roots_availability") return [true];
  assert.equal(command, "plugin:clipboard-manager|write_text");
  writes++;
  if (denied) throw new Error("native refusal private detail");
  clipboard = args!.text!;
  if (deferred) await new Promise<void>(resolve => completions.push(resolve));
} };
const { TauriStorageSettings } = await import("../tauri/TauriStorageSettings");
const { LocaleProvider, t } = await import("../lib/i18n");
const root = createRoot(document.getElementById("root")!);
const render = async (workspaceRoot: string) => { await act(async () => root.render(<LocaleProvider><TauriStorageSettings workspaceRoot={workspaceRoot} defaultWorkspace="/default" /></LocaleProvider>)); };
const label = t("settings.storage.currentWorkspace");
const copy = () => [...document.querySelectorAll<HTMLButtonElement>(".tauri-storage-path button")].find(button => button.getAttribute("aria-label") === t("settings.storage.copyLabel", { label }))!;
const refresh = () => [...document.querySelectorAll<HTMLButtonElement>("button")].find(button => button.textContent === t("settings.storage.refresh"))!;
await render("/workspace-a");
await act(async () => copy().click());
assert.equal(clipboard, "/workspace-a");
assert.equal(copy().title, t("settings.storage.copied"));
denied = true;
await act(async () => copy().click());
assert.equal(copy().title, t("settings.storage.copyPath"), "refusal clears old success");
assert.ok(document.querySelector('[role="alert"]')?.textContent?.includes(t("settings.storage.copyFailed", { label })));
assert.ok(!document.body.textContent?.includes("private detail"));
denied = false; deferred = true;
const before = writes;
await act(async () => { copy().click(); copy().click(); });
assert.equal(writes, before + 1, "synchronous duplicate click writes only once");
assert.equal(copy().disabled, true, "pending native write disables path copy");
await render("/workspace-b");
assert.equal(copy().disabled, false, "new path can own a new request");
await act(async () => copy().click());
assert.equal(clipboard, "/workspace-b");
await act(async () => completions.shift()!());
assert.equal(copy().title, t("settings.storage.copyPath"), "old completion cannot label new path copied");
assert.equal(copy().disabled, true, "old completion cannot release new write");
await act(async () => completions.shift()!());
assert.equal(copy().title, t("settings.storage.copied"));
await act(async () => copy().click());
failLoad = true;
await act(async () => refresh().click());
await act(async () => completions.shift()!());
assert.match(document.querySelector('[role="alert"]')?.textContent ?? "", /storage load failed/, "refresh failure survives old copy completion");
assert.equal(fallbackCalls, 0, "native refusal never uses browser clipboard");
await act(async () => root.unmount());
console.log("Storage native clipboard refusal, duplicate click and source/refresh ownership: OK");
