import assert from "node:assert/strict";
import { JSDOM } from "jsdom";
import type { RemoteControllerLease } from "../lib/remoteControllerPool";
import type { BridgeRemoteControllerSessionView } from "../lib/bridgeProtocol.generated";

const dom=new JSDOM("<body><div id='root'></div></body>",{url:"http://localhost/",pretendToBeVisual:true});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,Event:dom.window.Event,localStorage:dom.window.localStorage,IS_REACT_ACT_ENVIRONMENT:true});
Object.defineProperty(globalThis,"navigator",{value:dom.window.navigator,configurable:true});
const React=await import("react");const {act}=React;const {createRoot}=await import("react-dom/client");
const {LocaleProvider}=await import("../lib/i18n");const {TauriRemoteHistory}=await import("../tauri/TauriRemoteHistory");
const root=createRoot(document.getElementById("root")!);
const tick=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
const controller={id:"owned-controller",name:"owned",workspace:"/resolved",readOnly:true};
const gates:{path:string;resolve:(view:BridgeRemoteControllerSessionView)=>void;reject:(error:unknown)=>void}[]=[];
const lease:RemoteControllerLease={sessionImage:async()=>({url:"",errorCode:"not-found"}),ready:Promise.resolve(controller),sessions:async()=>[],release:()=>{},sessionView:path=>new Promise((resolve,reject)=>gates.push({path,resolve,reject}))};
const snapshot=(path:string):BridgeRemoteControllerSessionView=>({protocolVersion:1,sessionPath:path,readOnly:true,ownership:"saved",current:false,modelRef:"",label:"",history:[]});
const close=()=>{};
const render=async(path:string)=>act(async()=>{root.render(<LocaleProvider><TauriRemoteHistory lease={lease} controller={controller} sessionPath={path} title={path} onClose={close}/></LocaleProvider>);await tick();});
await render("/old.jsonl");assert.equal(gates.length,1);
await render("/new.jsonl");assert.equal(gates.length,2);
await act(async()=>{gates[1].resolve(snapshot("/new.jsonl"));await tick();});
assert.ok(document.body.textContent?.includes("no displayable messages"));
await act(async()=>{gates[0].reject(new Error("PRIVATE OLD FAILURE"));await tick();});
assert.equal(document.querySelector('[role="alert"]'),null,"old failure/finally cannot override new result");
assert.ok(!document.querySelector('[aria-busy="true"]'));
const refresh=()=>[...document.querySelectorAll<HTMLButtonElement>("button")].find(button=>button.textContent==="Refresh history")!;
await act(async()=>{refresh().click();await tick();});assert.equal(gates.length,3);assert.ok(refresh().disabled);
await act(async()=>{gates[2].reject(new Error("PRIVATE CURRENT FAILURE"));await tick();});
assert.match(document.querySelector('[role="alert"]')?.textContent ?? "",/Upgrade remote Serve/);
assert.ok(!document.body.textContent?.includes("PRIVATE"));
await act(async()=>{refresh().click();await tick();});assert.equal(gates.length,4);
await act(async()=>root.unmount());
await act(async()=>{gates[3].resolve(snapshot("/new.jsonl"));await tick();});
assert.equal(document.getElementById("root")?.children.length,0);dom.window.close();
console.log("Remote history UI ownership: old failure/finally, refresh guard, fixed errors, empty state and unmount passed");
