// Code generated by cmd/desktop-bridge-protocol-gen from docs/tauri/protocol/v1.schema.json. DO NOT EDIT.

export interface BridgeAnswerQuestionRequest {
  answers: BridgeAskAnswer[];
  id: string;
}

export interface BridgeApprovalRequest {
  allow: boolean;
  id: string;
}

export interface BridgeAskAnswer {
  questionId: string;
  selected: string[];
}

export interface BridgeAttachFileRequest {
  path: string;
  sessionId: string;
}

export interface BridgeAttachment {
  isImage: boolean;
  name: string;
  path: string;
  size: number;
}

export interface BridgeAttachmentResponse {
  attachment: BridgeAttachment;
  protocolVersion: number;
}

export interface BridgeDeleteSessionResponse {
  deleted: boolean;
  protocolVersion: number;
  sessionId: string;
}

export interface BridgeError {
  error: BridgeErrorBody;
  protocolVersion: number;
}

export interface BridgeErrorBody {
  code: "unauthenticated" | "invalid_request" | "not_found" | "conflict" | "resync_required" | "shutting_down" | "internal";
  message: string;
}

export interface BridgeEvent {
  eventKind: string;
  payload: Record<string, unknown>;
  protocolVersion: number;
  sequence: number;
  sessionId: string;
  tabId?: string;
}

export interface BridgeHealth {
  capabilities: string[];
  protocolVersion: number;
  sidecarInstanceId: string;
  status: "ok";
}

export interface BridgeHistoryMessage {
  content: string;
  role: "user" | "assistant";
  truncated?: boolean;
}

export interface BridgeHistoryResponse {
  messages: BridgeHistoryMessage[];
  protocolVersion: number;
  sequence: number;
  session: BridgeSession;
  startIndex: number;
  totalMessages: number;
}

export interface BridgeMCPInteractionAnswerRequest {
  action: "accept" | "decline" | "cancel";
  content?: Record<string, unknown>;
  id: string;
}

export interface BridgeOpenSessionRequest {
  sessionId: string;
  workspaceRoot?: string;
}

export interface BridgeProviderSummary {
  configured: boolean;
  displayName?: string;
  kind: string;
  modelCount: number;
  models: string[];
  name: string;
  requiresKey: boolean;
}

export interface BridgeProviderSummaryResponse {
  defaultModel: string;
  protocolVersion: number;
  providers: BridgeProviderSummary[];
}

export interface BridgeRenameSessionRequest {
  title: string;
}

export interface BridgeSession {
  id: string;
  path: string;
  state: "idle" | "running" | "paused";
  title?: string;
  workspaceRoot?: string;
}

export interface BridgeSessionResponse {
  protocolVersion: number;
  sequence?: number;
  session: BridgeSession;
}

export interface BridgeSetDefaultModelRequest {
  model: string;
}

export interface BridgeSubmitRequest {
  input: string;
}

export interface BridgeWorkspaceEntry {
  isDir: boolean;
  name: string;
  path: string;
}

export interface BridgeWorkspaceFilePreview {
  binary?: boolean;
  body?: string;
  error?: string;
  path: string;
  size: number;
  truncated?: boolean;
}

export interface BridgeWorkspaceFileRequest {
  path: string;
}

export interface BridgeWorkspaceFileResponse {
  preview: BridgeWorkspaceFilePreview;
  protocolVersion: number;
}

export interface BridgeWorkspaceListResponse {
  entries: BridgeWorkspaceEntry[];
  path: string;
  protocolVersion: number;
  truncated: boolean;
}

export interface BridgeWorkspaceRequest {
  path: string;
}
