// Code generated by cmd/desktop-bridge-protocol-gen from docs/tauri/protocol/v1.schema.json. DO NOT EDIT.

export interface BridgeAnswerQuestionRequest {
  answers: BridgeAskAnswer[];
  id: string;
}

export interface BridgeApprovalRequest {
  allow: boolean;
  id: string;
}

export interface BridgeAskAnswer {
  questionId: string;
  selected: string[];
}

export interface BridgeAttachFileRequest {
  path: string;
  sessionId: string;
}

export interface BridgeAttachment {
  isImage: boolean;
  name: string;
  path: string;
  size: number;
}

export interface BridgeAttachmentResponse {
  attachment: BridgeAttachment;
  protocolVersion: number;
}

export interface BridgeDeleteSessionResponse {
  deleted: boolean;
  protocolVersion: number;
  sessionId: string;
}

export interface BridgeError {
  error: BridgeErrorBody;
  protocolVersion: number;
}

export interface BridgeErrorBody {
  code: "unauthenticated" | "invalid_request" | "not_found" | "conflict" | "resync_required" | "shutting_down" | "internal";
  message: string;
}

export interface BridgeEvent {
  eventKind: string;
  payload: Record<string, unknown>;
  protocolVersion: number;
  sequence: number;
  sessionId: string;
  tabId?: string;
}

export interface BridgeHealth {
  capabilities: string[];
  protocolVersion: number;
  sidecarInstanceId: string;
  status: "ok";
}

export interface BridgeHistoryMessage {
  content: string;
  createdAtMs?: number;
  role: "user" | "assistant";
  truncated?: boolean;
  workDurationMs?: number;
}

export interface BridgeHistoryResponse {
  messages: BridgeHistoryMessage[];
  protocolVersion: number;
  sequence: number;
  session: BridgeSession;
  startIndex: number;
  totalMessages: number;
}

export interface BridgeMCPInteractionAnswerRequest {
  action: "accept" | "decline" | "cancel";
  content?: Record<string, unknown>;
  id: string;
}

export interface BridgeOpenSessionRequest {
  sessionId: string;
  workspaceRoot?: string;
}

export interface BridgeProjectFolder {
  root: string;
  title?: string;
}

export interface BridgeProjectFoldersResponse {
  projects: BridgeProjectFolder[];
  protocolVersion: number;
}

export interface BridgeProviderModelProbeRequest {
  apiKey?: string;
  model: string;
  name: string;
}

export interface BridgeProviderModelProbeResponse {
  latencyMillis: number;
  protocolVersion: number;
}

export interface BridgeProviderSummary {
  configured: boolean;
  displayName?: string;
  kind: string;
  modelCount: number;
  models: string[];
  name: string;
  requiresKey: boolean;
  searchModels: string[];
  visionModels: string[];
}

export interface BridgeProviderSummaryResponse {
  compactRatioPercent: number;
  defaultModel: string;
  plannerModel: string;
  protocolVersion: number;
  providers: BridgeProviderSummary[];
  reasoningLanguage: "auto" | "zh" | "en";
  scope: "global" | "project";
  visionModel: string;
  webSearchModel: string;
}

export interface BridgeRemoteBrowseEntry {
  isDir: boolean;
  modTime: number;
  name: string;
  path: string;
  size: number;
  symlink: boolean;
}

export interface BridgeRemoteBrowseRequest {
  name: string;
  path?: string;
}

export interface BridgeRemoteBrowseResponse {
  entries: BridgeRemoteBrowseEntry[];
  parentPath: string;
  path: string;
  protocolVersion: number;
  truncated: boolean;
}

export interface BridgeRemoteConnectRequest {
  name: string;
  passphrase?: string;
  password?: string;
  trustFingerprint?: string;
}

export interface BridgeRemoteConnectResponse {
  address?: string;
  fingerprint?: string;
  host?: string;
  keyType?: string;
  message?: string;
  protocolVersion: number;
  status: "connected" | "host_key_confirmation" | "failed";
}

export interface BridgeRemoteDisconnectRequest {
  name: string;
}

export interface BridgeRemoteDisconnectResponse {
  disconnected: boolean;
  name: string;
  protocolVersion: number;
}

export interface BridgeRemoteFilePreviewRequest {
  name: string;
  path: string;
}

export interface BridgeRemoteFilePreviewResponse {
  content: string;
  kind: "text" | "binary";
  path: string;
  protocolVersion: number;
  revision: string;
  truncated: boolean;
}

export interface BridgeRemoteFileSaveRequest {
  content: string;
  name: string;
  path: string;
  revision: string;
}

export interface BridgeRemoteFileSaveResponse {
  path: string;
  protocolVersion: number;
  revision: string;
}

export interface BridgeRenameSessionRequest {
  title: string;
}

export interface BridgeSession {
  id: string;
  modelRef?: string;
  path: string;
  state: "idle" | "running" | "paused";
  title?: string;
  workspaceRoot?: string;
}

export interface BridgeSessionMetrics {
  cacheHitTokens: number;
  cacheMissTokens: number;
  compactThresholdPercent: number;
  contextUsedTokens: number;
  contextWindowTokens: number;
}

export interface BridgeSessionResponse {
  metrics?: BridgeSessionMetrics;
  protocolVersion: number;
  sequence?: number;
  session: BridgeSession;
}

export interface BridgeSetAgentPreferenceRequest {
  compactRatioPercent?: number;
  reasoningLanguage?: "auto" | "zh" | "en";
  scope?: "global" | "project";
  workspaceRoot?: string;
}

export interface BridgeSetDefaultModelRequest {
  model: string;
  scope?: "global" | "project";
  workspaceRoot?: string;
}

export interface BridgeSetModelRoleRequest {
  model: string;
  role: "planner" | "vision" | "search";
  scope?: "global" | "project";
  workspaceRoot?: string;
}

export interface BridgeSetSessionModelRequest {
  model: string;
}

export interface BridgeSubmitRequest {
  input: string;
}

export interface BridgeWorkspaceChangeDetail {
  added?: number;
  binary?: boolean;
  diff?: string;
  removed?: number;
  source?: string;
  truncated?: boolean;
}

export interface BridgeWorkspaceChangeDetailRequest {
  path: string;
}

export interface BridgeWorkspaceChangeDetailResponse {
  detail: BridgeWorkspaceChangeDetail;
  protocolVersion: number;
}

export interface BridgeWorkspaceChangeView {
  canSessionRevert?: boolean;
  gitStatus?: string;
  latestPrompt?: string;
  latestTime?: number;
  oldPath?: string;
  path: string;
  sources: string[];
  turns?: number[];
}

export interface BridgeWorkspaceChanges {
  files: BridgeWorkspaceChangeView[];
  gitAvailable: boolean;
  gitBranch?: string;
  gitErr?: string;
}

export interface BridgeWorkspaceChangesResponse {
  changes: BridgeWorkspaceChanges;
  protocolVersion: number;
}

export interface BridgeWorkspaceEntry {
  isDir: boolean;
  name: string;
  path: string;
}

export interface BridgeWorkspaceFilePreview {
  binary?: boolean;
  body?: string;
  error?: string;
  path: string;
  size: number;
  truncated?: boolean;
}

export interface BridgeWorkspaceFileRequest {
  path: string;
}

export interface BridgeWorkspaceFileResponse {
  preview: BridgeWorkspaceFilePreview;
  protocolVersion: number;
}

export interface BridgeWorkspaceListResponse {
  entries: BridgeWorkspaceEntry[];
  path: string;
  protocolVersion: number;
  truncated: boolean;
}

export interface BridgeWorkspaceRequest {
  path: string;
}
