// Code generated by cmd/desktop-bridge-protocol-gen from docs/tauri/protocol/v1.schema.json. DO NOT EDIT.

export interface BridgeAnswerQuestionRequest {
  answers: BridgeAskAnswer[];
  id: string;
}

export interface BridgeApprovalRequest {
  allow: boolean;
  id: string;
}

export interface BridgeAskAnswer {
  questionId: string;
  selected: string[];
}

export interface BridgeAttachFileRequest {
  path: string;
  sessionId: string;
}

export interface BridgeAttachment {
  isImage: boolean;
  name: string;
  path: string;
  size: number;
}

export interface BridgeAttachmentResponse {
  attachment: BridgeAttachment;
  protocolVersion: number;
}

export interface BridgeCodeRewindCommitRequest {
  confirmPartialCoverage: boolean;
  planId: string;
}

export interface BridgeCodeRewindPlanResponse {
  plan: BridgeWorkspaceCodeRewindPlan;
  protocolVersion: number;
}

export interface BridgeCodeRewindPreviewRequest {
  turn: number;
}

export interface BridgeCombinedRewindCommitRequest {
  confirmPartialCoverage: boolean;
  planId: string;
}

export interface BridgeCombinedRewindPlanResponse {
  plan: BridgeWorkspaceCombinedRewindPlan;
  protocolVersion: number;
}

export interface BridgeCombinedRewindPreviewRequest {
  turn: number;
}

export interface BridgeCombinedRewindResultResponse {
  protocolVersion: number;
  result: BridgeWorkspaceCombinedRewindResult;
}

export interface BridgeConversationRewindCommitRequest {
  planId: string;
}

export interface BridgeConversationRewindPlanResponse {
  plan: BridgeWorkspaceConversationRewindPlan;
  protocolVersion: number;
}

export interface BridgeConversationRewindPreviewRequest {
  turn: number;
}

export interface BridgeConversationRewindResultResponse {
  protocolVersion: number;
  result: BridgeWorkspaceConversationRewindResult;
}

export interface BridgeConversationRewindUndoRequest {
  headId: string;
}

export interface BridgeDeleteSessionResponse {
  deleted: boolean;
  protocolVersion: number;
  sessionId: string;
}

export interface BridgeError {
  error: BridgeErrorBody;
  protocolVersion: number;
}

export interface BridgeErrorBody {
  code: "unauthenticated" | "invalid_request" | "not_found" | "conflict" | "resync_required" | "shutting_down" | "internal";
  message: string;
}

export interface BridgeEvent {
  eventKind: string;
  payload: Record<string, unknown>;
  protocolVersion: number;
  sequence: number;
  sessionId: string;
  tabId?: string;
}

export interface BridgeHealth {
  capabilities: string[];
  protocolVersion: number;
  sidecarInstanceId: string;
  status: "ok";
}

export interface BridgeHistoryMessage {
  content: string;
  createdAtMs?: number;
  role: "user" | "assistant";
  truncated?: boolean;
  turnUsage?: BridgeHistoryTurnUsage;
  workDurationMs?: number;
}

export interface BridgeHistoryResponse {
  messages: BridgeHistoryMessage[];
  protocolVersion: number;
  sequence: number;
  session: BridgeSession;
  startIndex: number;
  totalMessages: number;
}

export interface BridgeHistoryTurnUsage {
  cacheHitTokens?: number;
  cacheMissTokens?: number;
  complete: boolean;
  estimated: boolean;
  inputTokens: number;
  outputTokens: number;
  reasoningTokens: number;
  requestCount: number;
  totalTokens: number;
}

export interface BridgeLegacyConversationForkResult {
  error?: string;
  ok: boolean;
  sessionId?: string;
}

export interface BridgeLegacyConversationForkResultResponse {
  protocolVersion: number;
  result: BridgeLegacyConversationForkResult;
}

export interface BridgeMCPInteractionAnswerRequest {
  action: "accept" | "decline" | "cancel";
  content?: Record<string, unknown>;
  id: string;
}

export interface BridgeOpenSessionRequest {
  effort?: string;
  modelRef?: string;
  sessionId: string;
  workspaceRoot?: string;
}

export interface BridgeProjectFolder {
  root: string;
  title?: string;
}

export interface BridgeProjectFoldersResponse {
  projects: BridgeProjectFolder[];
  protocolVersion: number;
}

export interface BridgeProviderModelProbeRequest {
  apiKey?: string;
  model: string;
  name: string;
}

export interface BridgeProviderModelProbeResponse {
  latencyMillis: number;
  protocolVersion: number;
}

export interface BridgeProviderReasoningSummary {
  default: string;
  levels: string[];
  model: string;
  selected: string;
}

export interface BridgeProviderSummary {
  configured: boolean;
  displayName?: string;
  kind: string;
  modelCount: number;
  models: string[];
  name: string;
  reasoning?: BridgeProviderReasoningSummary[];
  requiresKey: boolean;
  searchModels: string[];
  visionModels: string[];
}

export interface BridgeProviderSummaryResponse {
  compactRatioPercent: number;
  defaultModel: string;
  plannerModel: string;
  protocolVersion: number;
  providers: BridgeProviderSummary[];
  reasoningLanguage: "auto" | "zh" | "en";
  scope: "global" | "project";
  visionModel: string;
  webSearchModel: string;
}

export interface BridgeRemoteBrowseEntry {
  isDir: boolean;
  modTime: number;
  name: string;
  path: string;
  size: number;
  symlink: boolean;
}

export interface BridgeRemoteBrowseRequest {
  name: string;
  path?: string;
}

export interface BridgeRemoteBrowseResponse {
  entries: BridgeRemoteBrowseEntry[];
  parentPath: string;
  path: string;
  protocolVersion: number;
  truncated: boolean;
}

export interface BridgeRemoteConnectRequest {
  name: string;
  passphrase?: string;
  password?: string;
  trustFingerprint?: string;
}

export interface BridgeRemoteConnectResponse {
  address?: string;
  fingerprint?: string;
  host?: string;
  keyType?: string;
  message?: string;
  protocolVersion: number;
  status: "connected" | "host_key_confirmation" | "failed";
}

export interface BridgeRemoteControllerCloseResponse {
  closed: boolean;
  protocolVersion: number;
}

export interface BridgeRemoteControllerHistoryMessage {
  content: string;
  missing?: string[];
  protocolRecovery?: BridgeRemoteControllerProtocolRecovery;
  reasoning?: string;
  role: "system" | "user" | "assistant" | "tool" | "notice" | "protocol_recovery" | "final_readiness";
  serverSearch?: BridgeRemoteControllerHistorySearch[];
  toolCallId?: string;
  toolCalls?: BridgeRemoteControllerHistoryToolCall[];
  toolName?: string;
}

export interface BridgeRemoteControllerHistorySearch {
  id: string;
  query?: string;
  results?: BridgeRemoteControllerHistorySearchHit[];
  sources_status?: string;
}

export interface BridgeRemoteControllerHistorySearchHit {
  title?: string;
  url?: string;
}

export interface BridgeRemoteControllerHistoryToolCall {
  arguments: string;
  id: string;
  name: string;
}

export interface BridgeRemoteControllerProtocolRecovery {
  id: string;
}

export interface BridgeRemoteControllerRequest {
  name: string;
  workspace: string;
}

export interface BridgeRemoteControllerResponse {
  controller: BridgeRemoteControllerView;
  protocolVersion: number;
}

export interface BridgeRemoteControllerRuntimeState {
  activity: string;
  backgroundJobs: number;
  cancelRequested: boolean;
  cancellable: boolean;
  pendingPrompt: boolean;
  phase: "idle" | "executing" | "finishing" | "closed";
  revision: number;
  running: boolean;
  runtimeEpoch: string;
  schemaVersion: number;
  turnEventSeq: number;
  turnId: string;
  turnStatus: "" | "queued" | "in_progress" | "waiting_user" | "cancelling" | "completed" | "interrupted" | "failed" | "protocol_failed";
}

export interface BridgeRemoteControllerSession {
  current: boolean;
  mtimeMilli: number;
  name: string;
  path: string;
  running: boolean;
  takenOver: boolean;
  title: string;
  turns: number;
}

export interface BridgeRemoteControllerSessionView {
  current: boolean;
  history: BridgeRemoteControllerHistoryMessage[];
  label: string;
  modelRef: string;
  ownership: "serve" | "saved" | "external";
  protocolVersion: number;
  readOnly: boolean;
  runtimeState?: BridgeRemoteControllerRuntimeState;
  sessionPath: string;
}

export interface BridgeRemoteControllerSessionViewRequest {
  sessionPath: string;
}

export interface BridgeRemoteControllerSessionViewResponse {
  controller: BridgeRemoteControllerView;
  protocolVersion: number;
  view: BridgeRemoteControllerSessionView;
}

export interface BridgeRemoteControllerSessionsResponse {
  controller: BridgeRemoteControllerView;
  protocolVersion: number;
  sessions: BridgeRemoteControllerSession[];
}

export interface BridgeRemoteControllerView {
  id: string;
  name: string;
  readOnly: boolean;
  workspace: string;
}

export interface BridgeRemoteDisconnectRequest {
  name: string;
}

export interface BridgeRemoteDisconnectResponse {
  disconnected: boolean;
  name: string;
  protocolVersion: number;
}

export interface BridgeRemoteFilePreviewRequest {
  name: string;
  path: string;
}

export interface BridgeRemoteFilePreviewResponse {
  content: string;
  kind: "text" | "binary";
  path: string;
  protocolVersion: number;
  revision: string;
  truncated: boolean;
}

export interface BridgeRemoteFileSaveRequest {
  content: string;
  name: string;
  path: string;
  revision: string;
}

export interface BridgeRemoteFileSaveResponse {
  path: string;
  protocolVersion: number;
  revision: string;
}

export interface BridgeRenameSessionRequest {
  title: string;
}

export interface BridgeSession {
  effort?: string;
  id: string;
  modelRef?: string;
  path: string;
  state: "idle" | "running" | "paused";
  title?: string;
  workspaceRoot?: string;
}

export interface BridgeSessionHeadSwitchRequest {
  headId: string;
}

export interface BridgeSessionHeadSwitchResponse {
  ok: boolean;
  protocolVersion: number;
}

export interface BridgeSessionHeadView {
  id: string;
  kind: string;
  messageCount: number;
  name?: string;
  parentId?: string;
  preview?: string;
  selected: boolean;
}

export interface BridgeSessionHeadsResponse {
  heads: BridgeSessionHeadView[];
  protocolVersion: number;
}

export interface BridgeSessionMetrics {
  cacheHitTokens: number;
  cacheMissTokens: number;
  compactThresholdPercent: number;
  contextUsedTokens: number;
  contextWindowTokens: number;
}

export interface BridgeSessionResponse {
  metrics?: BridgeSessionMetrics;
  protocolVersion: number;
  sequence?: number;
  session: BridgeSession;
}

export interface BridgeSetAgentPreferenceRequest {
  compactRatioPercent?: number;
  reasoningLanguage?: "auto" | "zh" | "en";
  scope?: "global" | "project";
  workspaceRoot?: string;
}

export interface BridgeSetDefaultModelRequest {
  model: string;
  scope?: "global" | "project";
  workspaceRoot?: string;
}

export interface BridgeSetModelRoleRequest {
  model: string;
  role: "planner" | "vision" | "search";
  scope?: "global" | "project";
  workspaceRoot?: string;
}

export interface BridgeSetSessionModelRequest {
  effort?: string;
  model: string;
}

export interface BridgeSubmitRequest {
  input: string;
}

export interface BridgeTerminalActionResponse {
  accepted: boolean;
  protocolVersion: number;
  terminalId: string;
}

export interface BridgeTerminalCreateRequest {
  path?: string;
  shellId?: string;
}

export interface BridgeTerminalExitView {
  exitCode: number;
  id: string;
  removed: boolean;
}

export interface BridgeTerminalInputRequest {
  data: string;
}

export interface BridgeTerminalOutputResponse {
  output: BridgeTerminalOutputView;
  protocolVersion: number;
}

export interface BridgeTerminalOutputView {
  data: string;
  end: number;
  id: string;
  start: number;
}

export interface BridgeTerminalRenameRequest {
  title: string;
}

export interface BridgeTerminalResizeRequest {
  cols: number;
  rows: number;
}

export interface BridgeTerminalSessionResponse {
  protocolVersion: number;
  terminal: BridgeTerminalSessionView;
}

export interface BridgeTerminalSessionView {
  createdAt: number;
  cwd: string;
  exitCode?: number;
  id: string;
  running: boolean;
  shell: string;
  title: string;
}

export interface BridgeTerminalShellView {
  id: string;
  label: string;
}

export interface BridgeTerminalWorkspaceResponse {
  protocolVersion: number;
  workspace: BridgeTerminalWorkspaceView;
}

export interface BridgeTerminalWorkspaceView {
  available: boolean;
  readOnly: boolean;
  reason?: string;
  sessions: BridgeTerminalSessionView[];
  shells: BridgeTerminalShellView[];
}

export interface BridgeWorkspaceChangeDetail {
  added?: number;
  binary?: boolean;
  diff?: string;
  removed?: number;
  source?: string;
  truncated?: boolean;
}

export interface BridgeWorkspaceChangeDetailRequest {
  path: string;
}

export interface BridgeWorkspaceChangeDetailResponse {
  detail: BridgeWorkspaceChangeDetail;
  protocolVersion: number;
}

export interface BridgeWorkspaceChangeView {
  canSessionRevert?: boolean;
  gitStatus?: string;
  latestPrompt?: string;
  latestTime?: number;
  oldPath?: string;
  path: string;
  sources: string[];
  turns?: number[];
}

export interface BridgeWorkspaceChanges {
  files: BridgeWorkspaceChangeView[];
  gitAvailable: boolean;
  gitBranch?: string;
  gitErr?: string;
}

export interface BridgeWorkspaceChangesResponse {
  changes: BridgeWorkspaceChanges;
  protocolVersion: number;
}

export interface BridgeWorkspaceCheckpointView {
  prompt: string;
  time: number;
  turn: number;
  turnFileCount: number;
}

export interface BridgeWorkspaceCheckpointsResponse {
  checkpoints: BridgeWorkspaceCheckpointView[];
  protocolVersion: number;
}

export interface BridgeWorkspaceCodeRewindPlan {
  canFiles: boolean;
  conflicts: string[];
  coverage: string;
  coverageGaps: string[];
  disabledReason?: string;
  fileCount: number;
  files: string[];
  filesTruncated: boolean;
  planId?: string;
  requiresCoverageConfirmation: boolean;
  turn: number;
}

export interface BridgeWorkspaceCombinedRewindPlan {
  canConversation: boolean;
  canFiles: boolean;
  conflicts: string[];
  coverageGaps: string[];
  disabledReason?: string;
  fileCount: number;
  files: string[];
  filesTruncated: boolean;
  planId?: string;
  requiresCoverageConfirmation: boolean;
  turn: number;
}

export interface BridgeWorkspaceCombinedRewindResult {
  conflicts: string[];
  conversationForked: boolean;
  deletedCount: number;
  error?: string;
  filesRestored: boolean;
  headId?: string;
  ok: boolean;
  partial: boolean;
  transactionId?: string;
  undoAvailable: boolean;
  writtenCount: number;
}

export interface BridgeWorkspaceConversationRewindPlan {
  canConversation: boolean;
  disabledReason?: string;
  planId?: string;
  turn: number;
}

export interface BridgeWorkspaceConversationRewindResult {
  conversationForked: boolean;
  error?: string;
  headId?: string;
  ok: boolean;
}

export interface BridgeWorkspaceEntry {
  isDir: boolean;
  name: string;
  path: string;
}

export interface BridgeWorkspaceFilePreview {
  binary?: boolean;
  body?: string;
  error?: string;
  path: string;
  size: number;
  truncated?: boolean;
}

export interface BridgeWorkspaceFileRequest {
  path: string;
}

export interface BridgeWorkspaceFileResponse {
  preview: BridgeWorkspaceFilePreview;
  protocolVersion: number;
}

export interface BridgeWorkspaceFileRevertCommitRequest {
  planId: string;
  resolution: "" | "overwrite_checkpoint";
}

export interface BridgeWorkspaceFileRevertPlan {
  canFiles: boolean;
  conflicts?: string[];
  disabledReason?: string;
  legacy?: boolean;
  path: string;
  planId?: string;
}

export interface BridgeWorkspaceFileRevertPlanResponse {
  plan: BridgeWorkspaceFileRevertPlan;
  protocolVersion: number;
}

export interface BridgeWorkspaceFileRevertResult {
  conflicts?: string[];
  deletedCount: number;
  error?: string;
  ok: boolean;
  transactionId?: string;
  undoAvailable: boolean;
  writtenCount: number;
}

export interface BridgeWorkspaceFileRevertResultResponse {
  protocolVersion: number;
  result: BridgeWorkspaceFileRevertResult;
}

export interface BridgeWorkspaceFileRevertUndoRequest {
  transactionId: string;
}

export interface BridgeWorkspaceImageRequest {
  source: string;
}

export interface BridgeWorkspaceImageResponse {
  image: BridgeWorkspaceImageView;
  protocolVersion: number;
}

export interface BridgeWorkspaceImageView {
  errorCode?: string;
  filename?: string;
  mime?: "image/png";
  openHref?: string;
  size?: number;
  url: string;
}

export interface BridgeWorkspaceListResponse {
  entries: BridgeWorkspaceEntry[];
  path: string;
  protocolVersion: number;
  truncated: boolean;
}

export interface BridgeWorkspaceRequest {
  path: string;
}

export interface BridgeWorkspaceTargetResponse {
  protocolVersion: number;
  sessionId: string;
  workspaceRoot: string;
}
